[Fri May 21 22:02:26.838132 2021] [wsgi:error] [pid 13399:tid 140719200409344] [remote ::1:34300] [2021-05-21 22:02:26,836] ERROR in app: Exception on /emotion_prediction [POST]
[Fri May 21 22:02:26.838178 2021] [wsgi:error] [pid 13399:tid 140719200409344] [remote ::1:34300] Traceback (most recent call last):
[Fri May 21 22:02:26.838183 2021] [wsgi:error] [pid 13399:tid 140719200409344] [remote ::1:34300]   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2051, in wsgi_app
[Fri May 21 22:02:26.838186 2021] [wsgi:error] [pid 13399:tid 140719200409344] [remote ::1:34300]     response = self.full_dispatch_request()
[Fri May 21 22:02:26.838189 2021] [wsgi:error] [pid 13399:tid 140719200409344] [remote ::1:34300]   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1501, in full_dispatch_request
[Fri May 21 22:02:26.838191 2021] [wsgi:error] [pid 13399:tid 140719200409344] [remote ::1:34300]     rv = self.handle_user_exception(e)
[Fri May 21 22:02:26.838194 2021] [wsgi:error] [pid 13399:tid 140719200409344] [remote ::1:34300]   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1499, in full_dispatch_request
[Fri May 21 22:02:26.838197 2021] [wsgi:error] [pid 13399:tid 140719200409344] [remote ::1:34300]     rv = self.dispatch_request()
[Fri May 21 22:02:26.838201 2021] [wsgi:error] [pid 13399:tid 140719200409344] [remote ::1:34300]   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1485, in dispatch_request
[Fri May 21 22:02:26.838204 2021] [wsgi:error] [pid 13399:tid 140719200409344] [remote ::1:34300]     return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
[Fri May 21 22:02:26.838208 2021] [wsgi:error] [pid 13399:tid 140719200409344] [remote ::1:34300]   File "/home/copes/graduation-project/Web/app.py", line 45, in emotion_prediction
[Fri May 21 22:02:26.838213 2021] [wsgi:error] [pid 13399:tid 140719200409344] [remote ::1:34300]     model = load_model('models/model_best_0_2.h5') # model load linux \xec\x97\x90\xec\x84\x9c\xeb\x8a\x94 \xeb\xb0\x91\xec\x97\x90\xec\x84\x9c\xed\x95\x98\xeb\x8a\x94 \xea\xb2\x83\xeb\xa7\x8c\xec\x9c\xbc\xeb\xa1\x9c\xeb\x8a\x94 \xec\x97\x90\xeb\x9f\xac\xea\xb0\x80 \xeb\xb0\x9c\xec\x83\x9d\xed\x95\x98\xec\x97\xac \xeb\x84\xa3\xec\x9d\x8c.
[Fri May 21 22:02:26.838217 2021] [wsgi:error] [pid 13399:tid 140719200409344] [remote ::1:34300]   File "/usr/local/lib/python3.8/dist-packages/keras/saving/save.py", line 206, in load_model
[Fri May 21 22:02:26.838220 2021] [wsgi:error] [pid 13399:tid 140719200409344] [remote ::1:34300]     return saved_model_load.load(filepath, compile, options)
[Fri May 21 22:02:26.838223 2021] [wsgi:error] [pid 13399:tid 140719200409344] [remote ::1:34300]   File "/usr/local/lib/python3.8/dist-packages/keras/saving/saved_model/load.py", line 109, in load
[Fri May 21 22:02:26.838225 2021] [wsgi:error] [pid 13399:tid 140719200409344] [remote ::1:34300]     meta_graph_def = loader_impl.parse_saved_model(path).meta_graphs[0]
[Fri May 21 22:02:26.838228 2021] [wsgi:error] [pid 13399:tid 140719200409344] [remote ::1:34300]   File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/saved_model/loader_impl.py", line 113, in parse_saved_model
[Fri May 21 22:02:26.838231 2021] [wsgi:error] [pid 13399:tid 140719200409344] [remote ::1:34300]     raise IOError(
[Fri May 21 22:02:26.838233 2021] [wsgi:error] [pid 13399:tid 140719200409344] [remote ::1:34300] OSError: SavedModel file does not exist at: models/model_best_0_2.h5/{saved_model.pbtxt|saved_model.pb}
2021-05-21 22:02:18.400009: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2021-05-21 22:02:18.400029: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
[Sun May 23 18:19:20.997448 2021] [wsgi:error] [pid 13534:tid 140047466874624] [remote ::1:34302] [2021-05-23 18:19:20,994] ERROR in app: Exception on /emotion_prediction [POST]
[Sun May 23 18:19:20.997507 2021] [wsgi:error] [pid 13534:tid 140047466874624] [remote ::1:34302] Traceback (most recent call last):
[Sun May 23 18:19:20.997515 2021] [wsgi:error] [pid 13534:tid 140047466874624] [remote ::1:34302]   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2051, in wsgi_app
[Sun May 23 18:19:20.997521 2021] [wsgi:error] [pid 13534:tid 140047466874624] [remote ::1:34302]     response = self.full_dispatch_request()
[Sun May 23 18:19:20.997527 2021] [wsgi:error] [pid 13534:tid 140047466874624] [remote ::1:34302]   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1501, in full_dispatch_request
[Sun May 23 18:19:20.997532 2021] [wsgi:error] [pid 13534:tid 140047466874624] [remote ::1:34302]     rv = self.handle_user_exception(e)
[Sun May 23 18:19:20.997538 2021] [wsgi:error] [pid 13534:tid 140047466874624] [remote ::1:34302]   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1499, in full_dispatch_request
[Sun May 23 18:19:20.997543 2021] [wsgi:error] [pid 13534:tid 140047466874624] [remote ::1:34302]     rv = self.dispatch_request()
[Sun May 23 18:19:20.997548 2021] [wsgi:error] [pid 13534:tid 140047466874624] [remote ::1:34302]   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1485, in dispatch_request
[Sun May 23 18:19:20.997553 2021] [wsgi:error] [pid 13534:tid 140047466874624] [remote ::1:34302]     return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
[Sun May 23 18:19:20.997559 2021] [wsgi:error] [pid 13534:tid 140047466874624] [remote ::1:34302]   File "/home/copes/graduation-project/Web/app.py", line 45, in emotion_prediction
[Sun May 23 18:19:20.997565 2021] [wsgi:error] [pid 13534:tid 140047466874624] [remote ::1:34302]     model = load_model('models/model_best_0_2.h5') # model load linux \xec\x97\x90\xec\x84\x9c\xeb\x8a\x94 \xeb\xb0\x91\xec\x97\x90\xec\x84\x9c\xed\x95\x98\xeb\x8a\x94 \xea\xb2\x83\xeb\xa7\x8c\xec\x9c\xbc\xeb\xa1\x9c\xeb\x8a\x94 \xec\x97\x90\xeb\x9f\xac\xea\xb0\x80 \xeb\xb0\x9c\xec\x83\x9d\xed\x95\x98\xec\x97\xac \xeb\x84\xa3\xec\x9d\x8c.
[Sun May 23 18:19:20.997640 2021] [wsgi:error] [pid 13534:tid 140047466874624] [remote ::1:34302]   File "/usr/local/lib/python3.8/dist-packages/keras/saving/save.py", line 206, in load_model
[Sun May 23 18:19:20.997649 2021] [wsgi:error] [pid 13534:tid 140047466874624] [remote ::1:34302]     return saved_model_load.load(filepath, compile, options)
[Sun May 23 18:19:20.997656 2021] [wsgi:error] [pid 13534:tid 140047466874624] [remote ::1:34302]   File "/usr/local/lib/python3.8/dist-packages/keras/saving/saved_model/load.py", line 109, in load
[Sun May 23 18:19:20.997666 2021] [wsgi:error] [pid 13534:tid 140047466874624] [remote ::1:34302]     meta_graph_def = loader_impl.parse_saved_model(path).meta_graphs[0]
[Sun May 23 18:19:20.997673 2021] [wsgi:error] [pid 13534:tid 140047466874624] [remote ::1:34302]   File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/saved_model/loader_impl.py", line 113, in parse_saved_model
[Sun May 23 18:19:20.997678 2021] [wsgi:error] [pid 13534:tid 140047466874624] [remote ::1:34302]     raise IOError(
[Sun May 23 18:19:20.997682 2021] [wsgi:error] [pid 13534:tid 140047466874624] [remote ::1:34302] OSError: SavedModel file does not exist at: models/model_best_0_2.h5/{saved_model.pbtxt|saved_model.pb}
2021-05-23 18:19:12.270715: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2021-05-23 18:19:12.270736: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
[Sun May 23 18:24:25.146641 2021] [wsgi:error] [pid 13666:tid 140631312271104] [remote ::1:34304] mod_wsgi (pid=13666): Failed to exec Python script file '/home/copes/graduation-project/Web/web.wsgi'.
[Sun May 23 18:24:25.146728 2021] [wsgi:error] [pid 13666:tid 140631312271104] [remote ::1:34304] mod_wsgi (pid=13666): Exception occurred processing WSGI script '/home/copes/graduation-project/Web/web.wsgi'.
[Sun May 23 18:24:25.147338 2021] [wsgi:error] [pid 13666:tid 140631312271104] [remote ::1:34304] Traceback (most recent call last):
[Sun May 23 18:24:25.147401 2021] [wsgi:error] [pid 13666:tid 140631312271104] [remote ::1:34304]   File "/home/copes/graduation-project/Web/web.wsgi", line 5, in <module>
[Sun May 23 18:24:25.147426 2021] [wsgi:error] [pid 13666:tid 140631312271104] [remote ::1:34304]     from app import app as application
[Sun May 23 18:24:25.147446 2021] [wsgi:error] [pid 13666:tid 140631312271104] [remote ::1:34304]   File "/home/copes/graduation-project/Web/app.py", line 9, in <module>
[Sun May 23 18:24:25.147468 2021] [wsgi:error] [pid 13666:tid 140631312271104] [remote ::1:34304]     model = load_model('models/model_best_0_2.h5') # model load linux \xec\x97\x90\xec\x84\x9c\xeb\x8a\x94 \xeb\xb0\x91\xec\x97\x90\xec\x84\x9c\xed\x95\x98\xeb\x8a\x94 \xea\xb2\x83\xeb\xa7\x8c\xec\x9c\xbc\xeb\xa1\x9c\xeb\x8a\x94 \xec\x97\x90\xeb\x9f\xac\xea\xb0\x80 \xeb\xb0\x9c\xec\x83\x9d\xed\x95\x98\xec\x97\xac \xeb\x84\xa3\xec\x9d\x8c.
[Sun May 23 18:24:25.147486 2021] [wsgi:error] [pid 13666:tid 140631312271104] [remote ::1:34304]   File "/usr/local/lib/python3.8/dist-packages/keras/saving/save.py", line 206, in load_model
[Sun May 23 18:24:25.147490 2021] [wsgi:error] [pid 13666:tid 140631312271104] [remote ::1:34304]     return saved_model_load.load(filepath, compile, options)
[Sun May 23 18:24:25.147499 2021] [wsgi:error] [pid 13666:tid 140631312271104] [remote ::1:34304]   File "/usr/local/lib/python3.8/dist-packages/keras/saving/saved_model/load.py", line 109, in load
[Sun May 23 18:24:25.147502 2021] [wsgi:error] [pid 13666:tid 140631312271104] [remote ::1:34304]     meta_graph_def = loader_impl.parse_saved_model(path).meta_graphs[0]
[Sun May 23 18:24:25.147510 2021] [wsgi:error] [pid 13666:tid 140631312271104] [remote ::1:34304]   File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/saved_model/loader_impl.py", line 113, in parse_saved_model
[Sun May 23 18:24:25.147513 2021] [wsgi:error] [pid 13666:tid 140631312271104] [remote ::1:34304]     raise IOError(
[Sun May 23 18:24:25.147528 2021] [wsgi:error] [pid 13666:tid 140631312271104] [remote ::1:34304] OSError: SavedModel file does not exist at: models/model_best_0_2.h5/{saved_model.pbtxt|saved_model.pb}
2021-05-23 18:24:23.798141: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2021-05-23 18:24:23.798161: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
[Sun May 23 18:29:26.854564 2021] [wsgi:error] [pid 13803:tid 139883498247936] [remote ::1:34306] [2021-05-23 18:29:26,853] ERROR in app: Exception on /emotion_prediction [POST]
[Sun May 23 18:29:26.854624 2021] [wsgi:error] [pid 13803:tid 139883498247936] [remote ::1:34306] Traceback (most recent call last):
[Sun May 23 18:29:26.854631 2021] [wsgi:error] [pid 13803:tid 139883498247936] [remote ::1:34306]   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2051, in wsgi_app
[Sun May 23 18:29:26.854635 2021] [wsgi:error] [pid 13803:tid 139883498247936] [remote ::1:34306]     response = self.full_dispatch_request()
[Sun May 23 18:29:26.854638 2021] [wsgi:error] [pid 13803:tid 139883498247936] [remote ::1:34306]   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1501, in full_dispatch_request
[Sun May 23 18:29:26.854642 2021] [wsgi:error] [pid 13803:tid 139883498247936] [remote ::1:34306]     rv = self.handle_user_exception(e)
[Sun May 23 18:29:26.854645 2021] [wsgi:error] [pid 13803:tid 139883498247936] [remote ::1:34306]   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1499, in full_dispatch_request
[Sun May 23 18:29:26.854648 2021] [wsgi:error] [pid 13803:tid 139883498247936] [remote ::1:34306]     rv = self.dispatch_request()
[Sun May 23 18:29:26.854651 2021] [wsgi:error] [pid 13803:tid 139883498247936] [remote ::1:34306]   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1485, in dispatch_request
[Sun May 23 18:29:26.854660 2021] [wsgi:error] [pid 13803:tid 139883498247936] [remote ::1:34306]     return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
[Sun May 23 18:29:26.854663 2021] [wsgi:error] [pid 13803:tid 139883498247936] [remote ::1:34306]   File "/home/copes/graduation-project/Web/app.py", line 58, in emotion_prediction
[Sun May 23 18:29:26.854666 2021] [wsgi:error] [pid 13803:tid 139883498247936] [remote ::1:34306]     face = face_detection.detectMultiScale(frame, scaleFactor = 1.1, minNeighbors = 5, minSize=(30, 30), flags = cv2.CASCADE_SCALE_IMAGE)
[Sun May 23 18:29:26.854669 2021] [wsgi:error] [pid 13803:tid 139883498247936] [remote ::1:34306] cv2.error: OpenCV(4.5.2) /tmp/pip-req-build-eirhwqtr/opencv/modules/objdetect/src/cascadedetect.cpp:1689: error: (-215:Assertion failed) !empty() in function 'detectMultiScale'
[Sun May 23 18:29:26.854672 2021] [wsgi:error] [pid 13803:tid 139883498247936] [remote ::1:34306] 
2021-05-23 18:29:25.024033: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2021-05-23 18:29:25.024054: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2021-05-23 18:29:26.475340: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2021-05-23 18:29:26.475357: W tensorflow/stream_executor/cuda/cuda_driver.cc:326] failed call to cuInit: UNKNOWN ERROR (303)
2021-05-23 18:29:26.475370: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (DESKTOP-MNQ7F8E): /proc/driver/nvidia/version does not exist
2021-05-23 18:29:26.475590: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
[Sun May 23 18:31:45.105937 2021] [wsgi:error] [pid 13951:tid 139981315217152] [remote ::1:34308] mod_wsgi (pid=13951): Failed to exec Python script file '/home/copes/graduation-project/Web/web.wsgi'.
[Sun May 23 18:31:45.106019 2021] [wsgi:error] [pid 13951:tid 139981315217152] [remote ::1:34308] mod_wsgi (pid=13951): Exception occurred processing WSGI script '/home/copes/graduation-project/Web/web.wsgi'.
[Sun May 23 18:31:45.106598 2021] [wsgi:error] [pid 13951:tid 139981315217152] [remote ::1:34308] Traceback (most recent call last):
[Sun May 23 18:31:45.106664 2021] [wsgi:error] [pid 13951:tid 139981315217152] [remote ::1:34308]   File "/home/copes/graduation-project/Web/web.wsgi", line 5, in <module>
[Sun May 23 18:31:45.106690 2021] [wsgi:error] [pid 13951:tid 139981315217152] [remote ::1:34308]     from app import app as application
[Sun May 23 18:31:45.106709 2021] [wsgi:error] [pid 13951:tid 139981315217152] [remote ::1:34308]   File "/home/copes/graduation-project/Web/app.py", line 9, in <module>
[Sun May 23 18:31:45.106714 2021] [wsgi:error] [pid 13951:tid 139981315217152] [remote ::1:34308]     model = load_model('./models/model_best_0_2.h5') # model load linux \xec\x97\x90\xec\x84\x9c\xeb\x8a\x94 \xeb\xb0\x91\xec\x97\x90\xec\x84\x9c\xed\x95\x98\xeb\x8a\x94 \xea\xb2\x83\xeb\xa7\x8c\xec\x9c\xbc\xeb\xa1\x9c\xeb\x8a\x94 \xec\x97\x90\xeb\x9f\xac\xea\xb0\x80 \xeb\xb0\x9c\xec\x83\x9d\xed\x95\x98\xec\x97\xac \xeb\x84\xa3\xec\x9d\x8c.
[Sun May 23 18:31:45.106723 2021] [wsgi:error] [pid 13951:tid 139981315217152] [remote ::1:34308]   File "/usr/local/lib/python3.8/dist-packages/keras/saving/save.py", line 206, in load_model
[Sun May 23 18:31:45.106727 2021] [wsgi:error] [pid 13951:tid 139981315217152] [remote ::1:34308]     return saved_model_load.load(filepath, compile, options)
[Sun May 23 18:31:45.106749 2021] [wsgi:error] [pid 13951:tid 139981315217152] [remote ::1:34308]   File "/usr/local/lib/python3.8/dist-packages/keras/saving/saved_model/load.py", line 109, in load
[Sun May 23 18:31:45.106760 2021] [wsgi:error] [pid 13951:tid 139981315217152] [remote ::1:34308]     meta_graph_def = loader_impl.parse_saved_model(path).meta_graphs[0]
[Sun May 23 18:31:45.106782 2021] [wsgi:error] [pid 13951:tid 139981315217152] [remote ::1:34308]   File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/saved_model/loader_impl.py", line 113, in parse_saved_model
[Sun May 23 18:31:45.106790 2021] [wsgi:error] [pid 13951:tid 139981315217152] [remote ::1:34308]     raise IOError(
[Sun May 23 18:31:45.106823 2021] [wsgi:error] [pid 13951:tid 139981315217152] [remote ::1:34308] OSError: SavedModel file does not exist at: ./models/model_best_0_2.h5/{saved_model.pbtxt|saved_model.pb}
2021-05-23 18:31:43.896493: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2021-05-23 18:31:43.896512: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
[Sun May 23 18:35:07.491139 2021] [wsgi:error] [pid 14082:tid 140575974057728] [remote ::1:34310] mod_wsgi (pid=14082): Failed to exec Python script file '/home/copes/graduation-project/Web/web.wsgi'.
[Sun May 23 18:35:07.491219 2021] [wsgi:error] [pid 14082:tid 140575974057728] [remote ::1:34310] mod_wsgi (pid=14082): Exception occurred processing WSGI script '/home/copes/graduation-project/Web/web.wsgi'.
[Sun May 23 18:35:07.491826 2021] [wsgi:error] [pid 14082:tid 140575974057728] [remote ::1:34310] Traceback (most recent call last):
[Sun May 23 18:35:07.491893 2021] [wsgi:error] [pid 14082:tid 140575974057728] [remote ::1:34310]   File "/home/copes/graduation-project/Web/web.wsgi", line 5, in <module>
[Sun May 23 18:35:07.491905 2021] [wsgi:error] [pid 14082:tid 140575974057728] [remote ::1:34310]     from app import app as application
[Sun May 23 18:35:07.491929 2021] [wsgi:error] [pid 14082:tid 140575974057728] [remote ::1:34310]   File "/home/copes/graduation-project/Web/app.py", line 9, in <module>
[Sun May 23 18:35:07.491937 2021] [wsgi:error] [pid 14082:tid 140575974057728] [remote ::1:34310]     model = load_model('./models/model_best_0_2.h5') # model load linux \xec\x97\x90\xec\x84\x9c\xeb\x8a\x94 \xeb\xb0\x91\xec\x97\x90\xec\x84\x9c\xed\x95\x98\xeb\x8a\x94 \xea\xb2\x83\xeb\xa7\x8c\xec\x9c\xbc\xeb\xa1\x9c\xeb\x8a\x94 \xec\x97\x90\xeb\x9f\xac\xea\xb0\x80 \xeb\xb0\x9c\xec\x83\x9d\xed\x95\x98\xec\x97\xac \xeb\x84\xa3\xec\x9d\x8c.
[Sun May 23 18:35:07.491955 2021] [wsgi:error] [pid 14082:tid 140575974057728] [remote ::1:34310]   File "/usr/local/lib/python3.8/dist-packages/keras/saving/save.py", line 206, in load_model
[Sun May 23 18:35:07.491962 2021] [wsgi:error] [pid 14082:tid 140575974057728] [remote ::1:34310]     return saved_model_load.load(filepath, compile, options)
[Sun May 23 18:35:07.491977 2021] [wsgi:error] [pid 14082:tid 140575974057728] [remote ::1:34310]   File "/usr/local/lib/python3.8/dist-packages/keras/saving/saved_model/load.py", line 109, in load
[Sun May 23 18:35:07.492008 2021] [wsgi:error] [pid 14082:tid 140575974057728] [remote ::1:34310]     meta_graph_def = loader_impl.parse_saved_model(path).meta_graphs[0]
[Sun May 23 18:35:07.492033 2021] [wsgi:error] [pid 14082:tid 140575974057728] [remote ::1:34310]   File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/saved_model/loader_impl.py", line 113, in parse_saved_model
[Sun May 23 18:35:07.492039 2021] [wsgi:error] [pid 14082:tid 140575974057728] [remote ::1:34310]     raise IOError(
[Sun May 23 18:35:07.492063 2021] [wsgi:error] [pid 14082:tid 140575974057728] [remote ::1:34310] OSError: SavedModel file does not exist at: ./models/model_best_0_2.h5/{saved_model.pbtxt|saved_model.pb}
[Sun May 23 18:35:17.526315 2021] [wsgi:error] [pid 14082:tid 140575940486912] [remote ::1:34312] mod_wsgi (pid=14082): Failed to exec Python script file '/home/copes/graduation-project/Web/web.wsgi'.
[Sun May 23 18:35:17.526411 2021] [wsgi:error] [pid 14082:tid 140575940486912] [remote ::1:34312] mod_wsgi (pid=14082): Exception occurred processing WSGI script '/home/copes/graduation-project/Web/web.wsgi'.
[Sun May 23 18:35:17.526699 2021] [wsgi:error] [pid 14082:tid 140575940486912] [remote ::1:34312] Traceback (most recent call last):
[Sun May 23 18:35:17.526866 2021] [wsgi:error] [pid 14082:tid 140575940486912] [remote ::1:34312]   File "/home/copes/graduation-project/Web/web.wsgi", line 5, in <module>
[Sun May 23 18:35:17.526882 2021] [wsgi:error] [pid 14082:tid 140575940486912] [remote ::1:34312]     from app import app as application
[Sun May 23 18:35:17.526905 2021] [wsgi:error] [pid 14082:tid 140575940486912] [remote ::1:34312]   File "/home/copes/graduation-project/Web/app.py", line 9, in <module>
[Sun May 23 18:35:17.526914 2021] [wsgi:error] [pid 14082:tid 140575940486912] [remote ::1:34312]     model = load_model('./models/model_best_0_2.h5') # model load linux \xec\x97\x90\xec\x84\x9c\xeb\x8a\x94 \xeb\xb0\x91\xec\x97\x90\xec\x84\x9c\xed\x95\x98\xeb\x8a\x94 \xea\xb2\x83\xeb\xa7\x8c\xec\x9c\xbc\xeb\xa1\x9c\xeb\x8a\x94 \xec\x97\x90\xeb\x9f\xac\xea\xb0\x80 \xeb\xb0\x9c\xec\x83\x9d\xed\x95\x98\xec\x97\xac \xeb\x84\xa3\xec\x9d\x8c.
[Sun May 23 18:35:17.526933 2021] [wsgi:error] [pid 14082:tid 140575940486912] [remote ::1:34312]   File "/usr/local/lib/python3.8/dist-packages/keras/saving/save.py", line 206, in load_model
[Sun May 23 18:35:17.526940 2021] [wsgi:error] [pid 14082:tid 140575940486912] [remote ::1:34312]     return saved_model_load.load(filepath, compile, options)
[Sun May 23 18:35:17.526956 2021] [wsgi:error] [pid 14082:tid 140575940486912] [remote ::1:34312]   File "/usr/local/lib/python3.8/dist-packages/keras/saving/saved_model/load.py", line 109, in load
[Sun May 23 18:35:17.526963 2021] [wsgi:error] [pid 14082:tid 140575940486912] [remote ::1:34312]     meta_graph_def = loader_impl.parse_saved_model(path).meta_graphs[0]
[Sun May 23 18:35:17.526979 2021] [wsgi:error] [pid 14082:tid 140575940486912] [remote ::1:34312]   File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/saved_model/loader_impl.py", line 113, in parse_saved_model
[Sun May 23 18:35:17.526987 2021] [wsgi:error] [pid 14082:tid 140575940486912] [remote ::1:34312]     raise IOError(
[Sun May 23 18:35:17.527033 2021] [wsgi:error] [pid 14082:tid 140575940486912] [remote ::1:34312] OSError: SavedModel file does not exist at: ./models/model_best_0_2.h5/{saved_model.pbtxt|saved_model.pb}
2021-05-23 18:35:06.292151: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2021-05-23 18:35:06.292181: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
[Sun May 23 18:36:13.407455 2021] [wsgi:error] [pid 14213:tid 140088985368320] [remote ::1:34316] [2021-05-23 18:36:13,406] ERROR in app: Exception on /emotion_prediction [POST]
[Sun May 23 18:36:13.407486 2021] [wsgi:error] [pid 14213:tid 140088985368320] [remote ::1:34316] Traceback (most recent call last):
[Sun May 23 18:36:13.407490 2021] [wsgi:error] [pid 14213:tid 140088985368320] [remote ::1:34316]   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2051, in wsgi_app
[Sun May 23 18:36:13.407494 2021] [wsgi:error] [pid 14213:tid 140088985368320] [remote ::1:34316]     response = self.full_dispatch_request()
[Sun May 23 18:36:13.407497 2021] [wsgi:error] [pid 14213:tid 140088985368320] [remote ::1:34316]   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1501, in full_dispatch_request
[Sun May 23 18:36:13.407500 2021] [wsgi:error] [pid 14213:tid 140088985368320] [remote ::1:34316]     rv = self.handle_user_exception(e)
[Sun May 23 18:36:13.407511 2021] [wsgi:error] [pid 14213:tid 140088985368320] [remote ::1:34316]   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1499, in full_dispatch_request
[Sun May 23 18:36:13.407514 2021] [wsgi:error] [pid 14213:tid 140088985368320] [remote ::1:34316]     rv = self.dispatch_request()
[Sun May 23 18:36:13.407516 2021] [wsgi:error] [pid 14213:tid 140088985368320] [remote ::1:34316]   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1485, in dispatch_request
[Sun May 23 18:36:13.407519 2021] [wsgi:error] [pid 14213:tid 140088985368320] [remote ::1:34316]     return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
[Sun May 23 18:36:13.407522 2021] [wsgi:error] [pid 14213:tid 140088985368320] [remote ::1:34316]   File "/home/copes/graduation-project/Web/app.py", line 46, in emotion_prediction
[Sun May 23 18:36:13.407525 2021] [wsgi:error] [pid 14213:tid 140088985368320] [remote ::1:34316]     model = load_model('./models/model_best_0_2.h5') # model load linux \xec\x97\x90\xec\x84\x9c\xeb\x8a\x94 \xeb\xb0\x91\xec\x97\x90\xec\x84\x9c\xed\x95\x98\xeb\x8a\x94 \xea\xb2\x83\xeb\xa7\x8c\xec\x9c\xbc\xeb\xa1\x9c\xeb\x8a\x94 \xec\x97\x90\xeb\x9f\xac\xea\xb0\x80 \xeb\xb0\x9c\xec\x83\x9d\xed\x95\x98\xec\x97\xac \xeb\x84\xa3\xec\x9d\x8c.
[Sun May 23 18:36:13.407528 2021] [wsgi:error] [pid 14213:tid 140088985368320] [remote ::1:34316]   File "/usr/local/lib/python3.8/dist-packages/keras/saving/save.py", line 206, in load_model
[Sun May 23 18:36:13.407531 2021] [wsgi:error] [pid 14213:tid 140088985368320] [remote ::1:34316]     return saved_model_load.load(filepath, compile, options)
[Sun May 23 18:36:13.407533 2021] [wsgi:error] [pid 14213:tid 140088985368320] [remote ::1:34316]   File "/usr/local/lib/python3.8/dist-packages/keras/saving/saved_model/load.py", line 109, in load
[Sun May 23 18:36:13.407536 2021] [wsgi:error] [pid 14213:tid 140088985368320] [remote ::1:34316]     meta_graph_def = loader_impl.parse_saved_model(path).meta_graphs[0]
[Sun May 23 18:36:13.407539 2021] [wsgi:error] [pid 14213:tid 140088985368320] [remote ::1:34316]   File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/saved_model/loader_impl.py", line 113, in parse_saved_model
[Sun May 23 18:36:13.407542 2021] [wsgi:error] [pid 14213:tid 140088985368320] [remote ::1:34316]     raise IOError(
[Sun May 23 18:36:13.407544 2021] [wsgi:error] [pid 14213:tid 140088985368320] [remote ::1:34316] OSError: SavedModel file does not exist at: ./models/model_best_0_2.h5/{saved_model.pbtxt|saved_model.pb}
2021-05-23 18:36:04.902195: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2021-05-23 18:36:04.902215: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
[Sun May 23 18:37:46.271426 2021] [wsgi:error] [pid 14346:tid 140618600625920] [remote ::1:34318] [2021-05-23 18:37:46,270] ERROR in app: Exception on /emotion_prediction [POST]
[Sun May 23 18:37:46.271482 2021] [wsgi:error] [pid 14346:tid 140618600625920] [remote ::1:34318] Traceback (most recent call last):
[Sun May 23 18:37:46.271490 2021] [wsgi:error] [pid 14346:tid 140618600625920] [remote ::1:34318]   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2051, in wsgi_app
[Sun May 23 18:37:46.271494 2021] [wsgi:error] [pid 14346:tid 140618600625920] [remote ::1:34318]     response = self.full_dispatch_request()
[Sun May 23 18:37:46.271497 2021] [wsgi:error] [pid 14346:tid 140618600625920] [remote ::1:34318]   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1501, in full_dispatch_request
[Sun May 23 18:37:46.271501 2021] [wsgi:error] [pid 14346:tid 140618600625920] [remote ::1:34318]     rv = self.handle_user_exception(e)
[Sun May 23 18:37:46.271504 2021] [wsgi:error] [pid 14346:tid 140618600625920] [remote ::1:34318]   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1499, in full_dispatch_request
[Sun May 23 18:37:46.271513 2021] [wsgi:error] [pid 14346:tid 140618600625920] [remote ::1:34318]     rv = self.dispatch_request()
[Sun May 23 18:37:46.271516 2021] [wsgi:error] [pid 14346:tid 140618600625920] [remote ::1:34318]   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1485, in dispatch_request
[Sun May 23 18:37:46.271519 2021] [wsgi:error] [pid 14346:tid 140618600625920] [remote ::1:34318]     return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
[Sun May 23 18:37:46.271522 2021] [wsgi:error] [pid 14346:tid 140618600625920] [remote ::1:34318]   File "/home/copes/graduation-project/Web/app.py", line 46, in emotion_prediction
[Sun May 23 18:37:46.271524 2021] [wsgi:error] [pid 14346:tid 140618600625920] [remote ::1:34318]     model = load_model('./models/model_best_0_2.h5')
[Sun May 23 18:37:46.271527 2021] [wsgi:error] [pid 14346:tid 140618600625920] [remote ::1:34318]   File "/usr/local/lib/python3.8/dist-packages/keras/saving/save.py", line 206, in load_model
[Sun May 23 18:37:46.271530 2021] [wsgi:error] [pid 14346:tid 140618600625920] [remote ::1:34318]     return saved_model_load.load(filepath, compile, options)
[Sun May 23 18:37:46.271532 2021] [wsgi:error] [pid 14346:tid 140618600625920] [remote ::1:34318]   File "/usr/local/lib/python3.8/dist-packages/keras/saving/saved_model/load.py", line 109, in load
[Sun May 23 18:37:46.271535 2021] [wsgi:error] [pid 14346:tid 140618600625920] [remote ::1:34318]     meta_graph_def = loader_impl.parse_saved_model(path).meta_graphs[0]
[Sun May 23 18:37:46.271538 2021] [wsgi:error] [pid 14346:tid 140618600625920] [remote ::1:34318]   File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/saved_model/loader_impl.py", line 113, in parse_saved_model
[Sun May 23 18:37:46.271542 2021] [wsgi:error] [pid 14346:tid 140618600625920] [remote ::1:34318]     raise IOError(
[Sun May 23 18:37:46.271544 2021] [wsgi:error] [pid 14346:tid 140618600625920] [remote ::1:34318] OSError: SavedModel file does not exist at: ./models/model_best_0_2.h5/{saved_model.pbtxt|saved_model.pb}
[Sun May 23 19:10:17.351038 2021] [wsgi:error] [pid 14346:tid 140618600625920] [remote ::1:34320] [2021-05-23 19:10:17,349] ERROR in app: Exception on /multi_upload_gan [POST]
[Sun May 23 19:10:17.351146 2021] [wsgi:error] [pid 14346:tid 140618600625920] [remote ::1:34320] Traceback (most recent call last):
[Sun May 23 19:10:17.351154 2021] [wsgi:error] [pid 14346:tid 140618600625920] [remote ::1:34320]   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2051, in wsgi_app
[Sun May 23 19:10:17.351158 2021] [wsgi:error] [pid 14346:tid 140618600625920] [remote ::1:34320]     response = self.full_dispatch_request()
[Sun May 23 19:10:17.351162 2021] [wsgi:error] [pid 14346:tid 140618600625920] [remote ::1:34320]   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1501, in full_dispatch_request
[Sun May 23 19:10:17.351165 2021] [wsgi:error] [pid 14346:tid 140618600625920] [remote ::1:34320]     rv = self.handle_user_exception(e)
[Sun May 23 19:10:17.351169 2021] [wsgi:error] [pid 14346:tid 140618600625920] [remote ::1:34320]   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1499, in full_dispatch_request
[Sun May 23 19:10:17.351172 2021] [wsgi:error] [pid 14346:tid 140618600625920] [remote ::1:34320]     rv = self.dispatch_request()
[Sun May 23 19:10:17.351175 2021] [wsgi:error] [pid 14346:tid 140618600625920] [remote ::1:34320]   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1485, in dispatch_request
[Sun May 23 19:10:17.351178 2021] [wsgi:error] [pid 14346:tid 140618600625920] [remote ::1:34320]     return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
[Sun May 23 19:10:17.351182 2021] [wsgi:error] [pid 14346:tid 140618600625920] [remote ::1:34320]   File "/home/copes/graduation-project/Web/app.py", line 32, in multi_upload_gan
[Sun May 23 19:10:17.351185 2021] [wsgi:error] [pid 14346:tid 140618600625920] [remote ::1:34320]     file.save("./static/GAN/{}.jpg".format(IDX))
[Sun May 23 19:10:17.351195 2021] [wsgi:error] [pid 14346:tid 140618600625920] [remote ::1:34320]   File "/usr/local/lib/python3.8/dist-packages/werkzeug/datastructures.py", line 3013, in save
[Sun May 23 19:10:17.351198 2021] [wsgi:error] [pid 14346:tid 140618600625920] [remote ::1:34320]     dst = open(dst, "wb")
[Sun May 23 19:10:17.351200 2021] [wsgi:error] [pid 14346:tid 140618600625920] [remote ::1:34320] FileNotFoundError: [Errno 2] No such file or directory: './static/GAN/0.jpg'
2021-05-23 18:37:44.918123: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2021-05-23 18:37:44.918143: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
[Sun May 23 19:26:10.599014 2021] [wsgi:error] [pid 14576:tid 140207166797568] [remote ::1:34338] [2021-05-23 19:26:10,597] ERROR in app: Exception on /emotion_prediction [POST]
[Sun May 23 19:26:10.599077 2021] [wsgi:error] [pid 14576:tid 140207166797568] [remote ::1:34338] Traceback (most recent call last):
[Sun May 23 19:26:10.599085 2021] [wsgi:error] [pid 14576:tid 140207166797568] [remote ::1:34338]   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2051, in wsgi_app
[Sun May 23 19:26:10.599090 2021] [wsgi:error] [pid 14576:tid 140207166797568] [remote ::1:34338]     response = self.full_dispatch_request()
[Sun May 23 19:26:10.599093 2021] [wsgi:error] [pid 14576:tid 140207166797568] [remote ::1:34338]   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1501, in full_dispatch_request
[Sun May 23 19:26:10.599097 2021] [wsgi:error] [pid 14576:tid 140207166797568] [remote ::1:34338]     rv = self.handle_user_exception(e)
[Sun May 23 19:26:10.599100 2021] [wsgi:error] [pid 14576:tid 140207166797568] [remote ::1:34338]   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1499, in full_dispatch_request
[Sun May 23 19:26:10.599104 2021] [wsgi:error] [pid 14576:tid 140207166797568] [remote ::1:34338]     rv = self.dispatch_request()
[Sun May 23 19:26:10.599107 2021] [wsgi:error] [pid 14576:tid 140207166797568] [remote ::1:34338]   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1485, in dispatch_request
[Sun May 23 19:26:10.599111 2021] [wsgi:error] [pid 14576:tid 140207166797568] [remote ::1:34338]     return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
[Sun May 23 19:26:10.599114 2021] [wsgi:error] [pid 14576:tid 140207166797568] [remote ::1:34338]   File "/home/copes/graduation-project/Web/app.py", line 46, in emotion_prediction
[Sun May 23 19:26:10.599118 2021] [wsgi:error] [pid 14576:tid 140207166797568] [remote ::1:34338]     model = load_model('./models/model_best_0_2.h5')
[Sun May 23 19:26:10.599121 2021] [wsgi:error] [pid 14576:tid 140207166797568] [remote ::1:34338]   File "/usr/local/lib/python3.8/dist-packages/keras/saving/save.py", line 206, in load_model
[Sun May 23 19:26:10.599125 2021] [wsgi:error] [pid 14576:tid 140207166797568] [remote ::1:34338]     return saved_model_load.load(filepath, compile, options)
[Sun May 23 19:26:10.599128 2021] [wsgi:error] [pid 14576:tid 140207166797568] [remote ::1:34338]   File "/usr/local/lib/python3.8/dist-packages/keras/saving/saved_model/load.py", line 109, in load
[Sun May 23 19:26:10.599132 2021] [wsgi:error] [pid 14576:tid 140207166797568] [remote ::1:34338]     meta_graph_def = loader_impl.parse_saved_model(path).meta_graphs[0]
[Sun May 23 19:26:10.599136 2021] [wsgi:error] [pid 14576:tid 140207166797568] [remote ::1:34338]   File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/saved_model/loader_impl.py", line 113, in parse_saved_model
[Sun May 23 19:26:10.599140 2021] [wsgi:error] [pid 14576:tid 140207166797568] [remote ::1:34338]     raise IOError(
[Sun May 23 19:26:10.599144 2021] [wsgi:error] [pid 14576:tid 140207166797568] [remote ::1:34338] OSError: SavedModel file does not exist at: ./models/model_best_0_2.h5/{saved_model.pbtxt|saved_model.pb}
[Sun May 23 19:28:17.494721 2021] [wsgi:error] [pid 14576:tid 140207166797568] [remote ::1:34340] [2021-05-23 19:28:17,493] ERROR in app: Exception on /multi_upload_gan [POST]
[Sun May 23 19:28:17.494783 2021] [wsgi:error] [pid 14576:tid 140207166797568] [remote ::1:34340] Traceback (most recent call last):
[Sun May 23 19:28:17.494792 2021] [wsgi:error] [pid 14576:tid 140207166797568] [remote ::1:34340]   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2051, in wsgi_app
[Sun May 23 19:28:17.494796 2021] [wsgi:error] [pid 14576:tid 140207166797568] [remote ::1:34340]     response = self.full_dispatch_request()
[Sun May 23 19:28:17.494800 2021] [wsgi:error] [pid 14576:tid 140207166797568] [remote ::1:34340]   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1501, in full_dispatch_request
[Sun May 23 19:28:17.494803 2021] [wsgi:error] [pid 14576:tid 140207166797568] [remote ::1:34340]     rv = self.handle_user_exception(e)
[Sun May 23 19:28:17.494807 2021] [wsgi:error] [pid 14576:tid 140207166797568] [remote ::1:34340]   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1499, in full_dispatch_request
[Sun May 23 19:28:17.494811 2021] [wsgi:error] [pid 14576:tid 140207166797568] [remote ::1:34340]     rv = self.dispatch_request()
[Sun May 23 19:28:17.494814 2021] [wsgi:error] [pid 14576:tid 140207166797568] [remote ::1:34340]   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1485, in dispatch_request
[Sun May 23 19:28:17.494818 2021] [wsgi:error] [pid 14576:tid 140207166797568] [remote ::1:34340]     return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
[Sun May 23 19:28:17.494821 2021] [wsgi:error] [pid 14576:tid 140207166797568] [remote ::1:34340]   File "/home/copes/graduation-project/Web/app.py", line 32, in multi_upload_gan
[Sun May 23 19:28:17.494825 2021] [wsgi:error] [pid 14576:tid 140207166797568] [remote ::1:34340]     file.save("./static/GAN/{}.jpg".format(IDX))
[Sun May 23 19:28:17.494828 2021] [wsgi:error] [pid 14576:tid 140207166797568] [remote ::1:34340]   File "/usr/local/lib/python3.8/dist-packages/werkzeug/datastructures.py", line 3013, in save
[Sun May 23 19:28:17.494831 2021] [wsgi:error] [pid 14576:tid 140207166797568] [remote ::1:34340]     dst = open(dst, "wb")
[Sun May 23 19:28:17.494835 2021] [wsgi:error] [pid 14576:tid 140207166797568] [remote ::1:34340] FileNotFoundError: [Errno 2] No such file or directory: './static/GAN/0.jpg'
2021-05-23 19:25:59.924681: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2021-05-23 19:25:59.924704: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
[Sun May 23 20:43:52.791575 2021] [wsgi:error] [pid 14834:tid 139945060435712] [remote ::1:34342] [[9.6297739e-03 9.1982674e-04 9.8945040e-01]]
2021-05-23 20:43:36.724602: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2021-05-23 20:43:36.724622: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2021-05-23 20:43:43.005623: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2021-05-23 20:43:43.005648: W tensorflow/stream_executor/cuda/cuda_driver.cc:326] failed call to cuInit: UNKNOWN ERROR (303)
2021-05-23 20:43:43.005670: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (DESKTOP-MNQ7F8E): /proc/driver/nvidia/version does not exist
2021-05-23 20:43:43.005934: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2021-05-23 20:43:43.719663: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:176] None of the MLIR Optimization Passes are enabled (registered 2)
2021-05-23 20:43:43.720319: I tensorflow/core/platform/profile_utils/cpu_utils.cc:114] CPU Frequency: 1991995000 Hz
[ WARN:0] global /tmp/pip-req-build-eirhwqtr/opencv/modules/imgcodecs/src/loadsave.cpp (693) imwrite_ imwrite_('home/copes/graduation-project/Web/static/Emotion/neutral/0.jpg'): can't open file for writing: permission denied
[Sun May 23 20:44:26.982657 2021] [wsgi:error] [pid 14834:tid 139945060435712] [remote ::1:34346] [[9.6297739e-03 9.1982674e-04 9.8945040e-01]]
[ WARN:0] global /tmp/pip-req-build-eirhwqtr/opencv/modules/imgcodecs/src/loadsave.cpp (693) imwrite_ imwrite_('home/copes/graduation-project/Web/static/Emotion/neutral/0.jpg'): can't open file for writing: permission denied
[Sun May 23 20:44:27.038017 2021] [wsgi:error] [pid 14834:tid 139945060435712] [remote ::1:34346] [[0.02050695 0.06258767 0.9169054 ]]
[ WARN:0] global /tmp/pip-req-build-eirhwqtr/opencv/modules/imgcodecs/src/loadsave.cpp (693) imwrite_ imwrite_('home/copes/graduation-project/Web/static/Emotion/neutral/1.jpg'): can't open file for writing: permission denied
[Sun May 23 20:44:27.101146 2021] [wsgi:error] [pid 14834:tid 139945060435712] [remote ::1:34346] [[0.1561424  0.00467606 0.83918154]]
[ WARN:0] global /tmp/pip-req-build-eirhwqtr/opencv/modules/imgcodecs/src/loadsave.cpp (693) imwrite_ imwrite_('home/copes/graduation-project/Web/static/Emotion/neutral/2.jpg'): can't open file for writing: permission denied
[Sun May 23 20:44:27.171380 2021] [wsgi:error] [pid 14834:tid 139945060435712] [remote ::1:34346] [[0.00845459 0.00888204 0.9826634 ]]
[ WARN:0] global /tmp/pip-req-build-eirhwqtr/opencv/modules/imgcodecs/src/loadsave.cpp (693) imwrite_ imwrite_('home/copes/graduation-project/Web/static/Emotion/neutral/3.jpg'): can't open file for writing: permission denied
[Sun May 23 20:44:27.237910 2021] [wsgi:error] [pid 14834:tid 139945060435712] [remote ::1:34346] [[4.597729e-02 3.666400e-04 9.536561e-01]]
[ WARN:0] global /tmp/pip-req-build-eirhwqtr/opencv/modules/imgcodecs/src/loadsave.cpp (693) imwrite_ imwrite_('home/copes/graduation-project/Web/static/Emotion/neutral/4.jpg'): can't open file for writing: permission denied
[Sun May 23 20:44:27.312619 2021] [wsgi:error] [pid 14834:tid 139945060435712] [remote ::1:34346] [[0.02591931 0.00367296 0.9704077 ]]
[ WARN:0] global /tmp/pip-req-build-eirhwqtr/opencv/modules/imgcodecs/src/loadsave.cpp (693) imwrite_ imwrite_('home/copes/graduation-project/Web/static/Emotion/neutral/5.jpg'): can't open file for writing: permission denied
[Sun May 23 20:44:27.382631 2021] [wsgi:error] [pid 14834:tid 139945060435712] [remote ::1:34346] [[0.00273046 0.0191434  0.9781261 ]]
[ WARN:0] global /tmp/pip-req-build-eirhwqtr/opencv/modules/imgcodecs/src/loadsave.cpp (693) imwrite_ imwrite_('home/copes/graduation-project/Web/static/Emotion/neutral/6.jpg'): can't open file for writing: permission denied
[Sun May 23 20:44:27.481957 2021] [wsgi:error] [pid 14834:tid 139945060435712] [remote ::1:34346] [[0.19477195 0.00555172 0.79967636]]
[ WARN:0] global /tmp/pip-req-build-eirhwqtr/opencv/modules/imgcodecs/src/loadsave.cpp (693) imwrite_ imwrite_('home/copes/graduation-project/Web/static/Emotion/neutral/7.jpg'): can't open file for writing: permission denied
[Sun May 23 20:44:27.558978 2021] [wsgi:error] [pid 14834:tid 139945060435712] [remote ::1:34346] [[0.0181159  0.00715475 0.9747293 ]]
[ WARN:0] global /tmp/pip-req-build-eirhwqtr/opencv/modules/imgcodecs/src/loadsave.cpp (693) imwrite_ imwrite_('home/copes/graduation-project/Web/static/Emotion/neutral/8.jpg'): can't open file for writing: permission denied
[Sun May 23 20:44:27.631815 2021] [wsgi:error] [pid 14834:tid 139945060435712] [remote ::1:34346] [[0.00215236 0.14575163 0.85209596]]
[ WARN:0] global /tmp/pip-req-build-eirhwqtr/opencv/modules/imgcodecs/src/loadsave.cpp (693) imwrite_ imwrite_('home/copes/graduation-project/Web/static/Emotion/neutral/9.jpg'): can't open file for writing: permission denied
[Sun May 23 20:44:27.704322 2021] [wsgi:error] [pid 14834:tid 139945060435712] [remote ::1:34346] [[0.01975805 0.00176907 0.9784728 ]]
[ WARN:0] global /tmp/pip-req-build-eirhwqtr/opencv/modules/imgcodecs/src/loadsave.cpp (693) imwrite_ imwrite_('home/copes/graduation-project/Web/static/Emotion/neutral/10.jpg'): can't open file for writing: permission denied
[Sun May 23 20:44:27.772597 2021] [wsgi:error] [pid 14834:tid 139945060435712] [remote ::1:34346] [[1.5929326e-01 6.4941193e-04 8.4005737e-01]]
[ WARN:0] global /tmp/pip-req-build-eirhwqtr/opencv/modules/imgcodecs/src/loadsave.cpp (693) imwrite_ imwrite_('home/copes/graduation-project/Web/static/Emotion/neutral/11.jpg'): can't open file for writing: permission denied
[Sun May 23 20:44:27.840372 2021] [wsgi:error] [pid 14834:tid 139945060435712] [remote ::1:34346] [[0.10447256 0.00173842 0.89378893]]
[ WARN:0] global /tmp/pip-req-build-eirhwqtr/opencv/modules/imgcodecs/src/loadsave.cpp (693) imwrite_ imwrite_('home/copes/graduation-project/Web/static/Emotion/neutral/12.jpg'): can't open file for writing: permission denied
[Sun May 23 20:44:27.902733 2021] [wsgi:error] [pid 14834:tid 139945060435712] [remote ::1:34346] [[1.9839752e-02 3.9648614e-04 9.7976375e-01]]
[ WARN:0] global /tmp/pip-req-build-eirhwqtr/opencv/modules/imgcodecs/src/loadsave.cpp (693) imwrite_ imwrite_('home/copes/graduation-project/Web/static/Emotion/neutral/13.jpg'): can't open file for writing: permission denied
[Sun May 23 20:44:27.970202 2021] [wsgi:error] [pid 14834:tid 139945060435712] [remote ::1:34346] [[4.0209842e-01 5.7689834e-04 5.9732479e-01]]
[ WARN:0] global /tmp/pip-req-build-eirhwqtr/opencv/modules/imgcodecs/src/loadsave.cpp (693) imwrite_ imwrite_('home/copes/graduation-project/Web/static/Emotion/neutral/14.jpg'): can't open file for writing: permission denied
[Sun May 23 20:44:28.042484 2021] [wsgi:error] [pid 14834:tid 139945060435712] [remote ::1:34346] [[0.02074791 0.01212754 0.9671245 ]]
[ WARN:0] global /tmp/pip-req-build-eirhwqtr/opencv/modules/imgcodecs/src/loadsave.cpp (693) imwrite_ imwrite_('home/copes/graduation-project/Web/static/Emotion/neutral/15.jpg'): can't open file for writing: permission denied
[Sun May 23 20:44:28.114860 2021] [wsgi:error] [pid 14834:tid 139945060435712] [remote ::1:34346] [[0.00525339 0.02359281 0.9711538 ]]
[ WARN:0] global /tmp/pip-req-build-eirhwqtr/opencv/modules/imgcodecs/src/loadsave.cpp (693) imwrite_ imwrite_('home/copes/graduation-project/Web/static/Emotion/neutral/16.jpg'): can't open file for writing: permission denied
[Sun May 23 20:44:28.179743 2021] [wsgi:error] [pid 14834:tid 139945060435712] [remote ::1:34346] [[0.0428966  0.03135791 0.9257454 ]]
[ WARN:0] global /tmp/pip-req-build-eirhwqtr/opencv/modules/imgcodecs/src/loadsave.cpp (693) imwrite_ imwrite_('home/copes/graduation-project/Web/static/Emotion/neutral/17.jpg'): can't open file for writing: permission denied
[Sun May 23 20:44:28.249561 2021] [wsgi:error] [pid 14834:tid 139945060435712] [remote ::1:34346] [[0.3347329  0.10236973 0.56289744]]
[ WARN:0] global /tmp/pip-req-build-eirhwqtr/opencv/modules/imgcodecs/src/loadsave.cpp (693) imwrite_ imwrite_('home/copes/graduation-project/Web/static/Emotion/neutral/18.jpg'): can't open file for writing: permission denied
[Sun May 23 20:44:28.393594 2021] [wsgi:error] [pid 14834:tid 139945060435712] [remote ::1:34346] [[1.2683483e-02 2.6598462e-04 9.8705053e-01]]
[ WARN:0] global /tmp/pip-req-build-eirhwqtr/opencv/modules/imgcodecs/src/loadsave.cpp (693) imwrite_ imwrite_('home/copes/graduation-project/Web/static/Emotion/neutral/19.jpg'): can't open file for writing: permission denied
[Sun May 23 20:44:28.464677 2021] [wsgi:error] [pid 14834:tid 139945060435712] [remote ::1:34346] [[9.351187e-03 5.857703e-04 9.900630e-01]]
[ WARN:0] global /tmp/pip-req-build-eirhwqtr/opencv/modules/imgcodecs/src/loadsave.cpp (693) imwrite_ imwrite_('home/copes/graduation-project/Web/static/Emotion/neutral/20.jpg'): can't open file for writing: permission denied
[Sun May 23 21:30:37.200322 2021] [wsgi:error] [pid 15105:tid 140271737095936] [remote ::1:34350] [[0.02050695 0.06258767 0.9169054 ]]
2021-05-23 21:30:09.039680: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2021-05-23 21:30:09.039700: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2021-05-23 21:30:28.338541: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2021-05-23 21:30:28.338557: W tensorflow/stream_executor/cuda/cuda_driver.cc:326] failed call to cuInit: UNKNOWN ERROR (303)
2021-05-23 21:30:28.338570: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (DESKTOP-MNQ7F8E): /proc/driver/nvidia/version does not exist
2021-05-23 21:30:28.338743: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2021-05-23 21:30:28.893223: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:176] None of the MLIR Optimization Passes are enabled (registered 2)
2021-05-23 21:30:28.893552: I tensorflow/core/platform/profile_utils/cpu_utils.cc:114] CPU Frequency: 1991995000 Hz
[ WARN:0] global /tmp/pip-req-build-eirhwqtr/opencv/modules/imgcodecs/src/loadsave.cpp (693) imwrite_ imwrite_('home/copes/graduation-project/Web/static/Emotion/neutral/0.jpg'): can't open file for writing: permission denied
[Sun May 23 21:30:37.270037 2021] [wsgi:error] [pid 15105:tid 140271737095936] [remote ::1:34350] [[0.1561424  0.00467606 0.83918154]]
[ WARN:0] global /tmp/pip-req-build-eirhwqtr/opencv/modules/imgcodecs/src/loadsave.cpp (693) imwrite_ imwrite_('home/copes/graduation-project/Web/static/Emotion/neutral/1.jpg'): can't open file for writing: permission denied
[Sun May 23 21:30:37.348022 2021] [wsgi:error] [pid 15105:tid 140271737095936] [remote ::1:34350] [[0.00845459 0.00888204 0.9826634 ]]
[ WARN:0] global /tmp/pip-req-build-eirhwqtr/opencv/modules/imgcodecs/src/loadsave.cpp (693) imwrite_ imwrite_('home/copes/graduation-project/Web/static/Emotion/neutral/2.jpg'): can't open file for writing: permission denied
[Sun May 23 21:30:37.418706 2021] [wsgi:error] [pid 15105:tid 140271737095936] [remote ::1:34350] [[4.597729e-02 3.666400e-04 9.536561e-01]]
[ WARN:0] global /tmp/pip-req-build-eirhwqtr/opencv/modules/imgcodecs/src/loadsave.cpp (693) imwrite_ imwrite_('home/copes/graduation-project/Web/static/Emotion/neutral/3.jpg'): can't open file for writing: permission denied
[Sun May 23 21:30:37.496640 2021] [wsgi:error] [pid 15105:tid 140271737095936] [remote ::1:34350] [[0.02591931 0.00367296 0.9704077 ]]
[ WARN:0] global /tmp/pip-req-build-eirhwqtr/opencv/modules/imgcodecs/src/loadsave.cpp (693) imwrite_ imwrite_('home/copes/graduation-project/Web/static/Emotion/neutral/4.jpg'): can't open file for writing: permission denied
[Sun May 23 21:30:37.569952 2021] [wsgi:error] [pid 15105:tid 140271737095936] [remote ::1:34350] [[0.00273046 0.0191434  0.9781261 ]]
[ WARN:0] global /tmp/pip-req-build-eirhwqtr/opencv/modules/imgcodecs/src/loadsave.cpp (693) imwrite_ imwrite_('home/copes/graduation-project/Web/static/Emotion/neutral/5.jpg'): can't open file for writing: permission denied
[Sun May 23 21:30:37.669621 2021] [wsgi:error] [pid 15105:tid 140271737095936] [remote ::1:34350] [[0.05130138 0.00247891 0.94621974]]
[ WARN:0] global /tmp/pip-req-build-eirhwqtr/opencv/modules/imgcodecs/src/loadsave.cpp (693) imwrite_ imwrite_('home/copes/graduation-project/Web/static/Emotion/neutral/6.jpg'): can't open file for writing: permission denied
[Sun May 23 21:30:37.744134 2021] [wsgi:error] [pid 15105:tid 140271737095936] [remote ::1:34350] [[0.0045835  0.00117963 0.9942368 ]]
[Sun May 23 21:30:37.819835 2021] [wsgi:error] [pid 15105:tid 140271737095936] [remote ::1:34350] [[4.8797271e-01 3.9616763e-04 5.1163113e-01]]
[Sun May 23 21:30:37.892291 2021] [wsgi:error] [pid 15105:tid 140271737095936] [remote ::1:34350] [[6.1493507e-03 6.6049478e-04 9.9319011e-01]]
[Sun May 23 21:30:37.961609 2021] [wsgi:error] [pid 15105:tid 140271737095936] [remote ::1:34350] [[7.2099008e-02 2.0876895e-04 9.2769223e-01]]
[Sun May 23 21:30:38.030686 2021] [wsgi:error] [pid 15105:tid 140271737095936] [remote ::1:34350] [[0.0311581  0.01410805 0.9547339 ]]
[Sun May 23 21:30:38.091376 2021] [wsgi:error] [pid 15105:tid 140271737095936] [remote ::1:34350] [[4.3041032e-02 1.7129301e-04 9.5678765e-01]]
[Sun May 23 21:30:38.188581 2021] [wsgi:error] [pid 15105:tid 140271737095936] [remote ::1:34350] [[0.19477195 0.00555172 0.79967636]]
[Sun May 23 21:30:38.259303 2021] [wsgi:error] [pid 15105:tid 140271737095936] [remote ::1:34350] [[0.0181159  0.00715475 0.9747293 ]]
[Sun May 23 21:30:38.335445 2021] [wsgi:error] [pid 15105:tid 140271737095936] [remote ::1:34350] [[0.00215236 0.14575163 0.85209596]]
[Sun May 23 21:30:38.407944 2021] [wsgi:error] [pid 15105:tid 140271737095936] [remote ::1:34350] [[0.01975805 0.00176907 0.9784728 ]]
[Sun May 23 21:30:38.476766 2021] [wsgi:error] [pid 15105:tid 140271737095936] [remote ::1:34350] [[1.5929326e-01 6.4941193e-04 8.4005737e-01]]
[Sun May 23 21:30:38.544911 2021] [wsgi:error] [pid 15105:tid 140271737095936] [remote ::1:34350] [[0.10447256 0.00173842 0.89378893]]
[Sun May 23 21:33:15.302943 2021] [wsgi:error] [pid 15105:tid 140271737095936] [remote ::1:34354] [[9.6297739e-03 9.1982674e-04 9.8945040e-01]]
[Sun May 23 21:33:15.364904 2021] [wsgi:error] [pid 15105:tid 140271737095936] [remote ::1:34354] [[0.02050695 0.06258767 0.9169054 ]]
[Sun May 23 21:33:15.460948 2021] [wsgi:error] [pid 15105:tid 140271737095936] [remote ::1:34354] [[0.1561424  0.00467606 0.83918154]]
[Sun May 23 21:33:15.557282 2021] [wsgi:error] [pid 15105:tid 140271737095936] [remote ::1:34354] [[0.00845459 0.00888204 0.9826634 ]]
[Sun May 23 21:33:15.631366 2021] [wsgi:error] [pid 15105:tid 140271737095936] [remote ::1:34354] [[4.597729e-02 3.666400e-04 9.536561e-01]]
[Sun May 23 21:33:15.708011 2021] [wsgi:error] [pid 15105:tid 140271737095936] [remote ::1:34354] [[0.02591931 0.00367296 0.9704077 ]]
[Sun May 23 21:33:15.775422 2021] [wsgi:error] [pid 15105:tid 140271737095936] [remote ::1:34354] [[0.00273046 0.0191434  0.9781261 ]]
[Sun May 23 21:33:15.878816 2021] [wsgi:error] [pid 15105:tid 140271737095936] [remote ::1:34354] [[0.05130138 0.00247891 0.94621974]]
[Sun May 23 21:33:15.947953 2021] [wsgi:error] [pid 15105:tid 140271737095936] [remote ::1:34354] [[0.0045835  0.00117963 0.9942368 ]]
[Sun May 23 21:33:16.019957 2021] [wsgi:error] [pid 15105:tid 140271737095936] [remote ::1:34354] [[4.8797271e-01 3.9616763e-04 5.1163113e-01]]
[Sun May 23 21:33:16.094489 2021] [wsgi:error] [pid 15105:tid 140271737095936] [remote ::1:34354] [[6.1493507e-03 6.6049478e-04 9.9319011e-01]]
[Sun May 23 21:33:16.160987 2021] [wsgi:error] [pid 15105:tid 140271737095936] [remote ::1:34354] [[7.2099008e-02 2.0876895e-04 9.2769223e-01]]
[Sun May 23 21:33:16.231174 2021] [wsgi:error] [pid 15105:tid 140271737095936] [remote ::1:34354] [[0.0311581  0.01410805 0.9547339 ]]
[Sun May 23 21:33:16.294991 2021] [wsgi:error] [pid 15105:tid 140271737095936] [remote ::1:34354] [[4.3041032e-02 1.7129301e-04 9.5678765e-01]]
[Sun May 23 21:33:16.392710 2021] [wsgi:error] [pid 15105:tid 140271737095936] [remote ::1:34354] [[0.19477195 0.00555172 0.79967636]]
[Sun May 23 21:33:16.467923 2021] [wsgi:error] [pid 15105:tid 140271737095936] [remote ::1:34354] [[0.0181159  0.00715475 0.9747293 ]]
[Sun May 23 21:33:16.542780 2021] [wsgi:error] [pid 15105:tid 140271737095936] [remote ::1:34354] [[0.00215236 0.14575163 0.85209596]]
[Sun May 23 21:33:16.617810 2021] [wsgi:error] [pid 15105:tid 140271737095936] [remote ::1:34354] [[0.01975805 0.00176907 0.9784728 ]]
[Sun May 23 21:33:16.692491 2021] [wsgi:error] [pid 15105:tid 140271737095936] [remote ::1:34354] [[1.5929326e-01 6.4941193e-04 8.4005737e-01]]
[Sun May 23 21:33:16.762635 2021] [wsgi:error] [pid 15105:tid 140271737095936] [remote ::1:34354] [[0.10447256 0.00173842 0.89378893]]
[Sun May 23 21:33:16.826352 2021] [wsgi:error] [pid 15105:tid 140271737095936] [remote ::1:34354] [[1.9839752e-02 3.9648614e-04 9.7976375e-01]]
[Sun May 23 21:33:16.892353 2021] [wsgi:error] [pid 15105:tid 140271737095936] [remote ::1:34354] [[4.0209842e-01 5.7689834e-04 5.9732479e-01]]
[Sun May 23 21:33:16.962923 2021] [wsgi:error] [pid 15105:tid 140271737095936] [remote ::1:34354] [[0.1287375  0.0066506  0.86461186]]
[Sun May 23 21:33:17.034659 2021] [wsgi:error] [pid 15105:tid 140271737095936] [remote ::1:34354] [[1.8442921e-02 3.1668242e-05 9.8152542e-01]]
[Sun May 23 21:33:17.110199 2021] [wsgi:error] [pid 15105:tid 140271737095936] [remote ::1:34354] [[0.11244605 0.03096933 0.85658467]]
[Sun May 23 21:33:17.184234 2021] [wsgi:error] [pid 15105:tid 140271737095936] [remote ::1:34354] [[0.31806996 0.00182547 0.68010455]]
[Sun May 23 21:33:17.260154 2021] [wsgi:error] [pid 15105:tid 140271737095936] [remote ::1:34354] [[1.0387175e-01 6.4992596e-04 8.9547831e-01]]
[Sun May 23 21:33:17.326888 2021] [wsgi:error] [pid 15105:tid 140271737095936] [remote ::1:34354] [[1.4036876e-01 2.9067480e-04 8.5934049e-01]]
[Sun May 23 21:33:17.395432 2021] [wsgi:error] [pid 15105:tid 140271737095936] [remote ::1:34354] [[0.03275191 0.08921272 0.8780354 ]]
[Sun May 23 21:33:17.459314 2021] [wsgi:error] [pid 15105:tid 140271737095936] [remote ::1:34354] [[0.11591227 0.00254197 0.8815458 ]]
[Sun May 23 21:33:17.534851 2021] [wsgi:error] [pid 15105:tid 140271737095936] [remote ::1:34354] [[0.13894767 0.2243983  0.6366541 ]]
[Sun May 23 21:33:17.624820 2021] [wsgi:error] [pid 15105:tid 140271737095936] [remote ::1:34354] [[0.00771133 0.00438042 0.9879083 ]]
[Sun May 23 21:33:17.711536 2021] [wsgi:error] [pid 15105:tid 140271737095936] [remote ::1:34354] [[5.4134727e-02 1.4948583e-04 9.4571579e-01]]
[Sun May 23 21:33:17.783542 2021] [wsgi:error] [pid 15105:tid 140271737095936] [remote ::1:34354] [[0.00515046 0.137072   0.85777754]]
[Sun May 23 21:33:17.864708 2021] [wsgi:error] [pid 15105:tid 140271737095936] [remote ::1:34354] [[0.02074791 0.01212754 0.9671245 ]]
[Sun May 23 21:33:17.931998 2021] [wsgi:error] [pid 15105:tid 140271737095936] [remote ::1:34354] [[0.00525339 0.02359281 0.9711538 ]]
[Sun May 23 21:33:17.997901 2021] [wsgi:error] [pid 15105:tid 140271737095936] [remote ::1:34354] [[0.0428966  0.03135791 0.9257454 ]]
[Sun May 23 21:33:18.065043 2021] [wsgi:error] [pid 15105:tid 140271737095936] [remote ::1:34354] [[0.3347329  0.10236973 0.56289744]]
[Sun May 23 21:33:18.210515 2021] [wsgi:error] [pid 15105:tid 140271737095936] [remote ::1:34354] [[1.2683483e-02 2.6598462e-04 9.8705053e-01]]
[Sun May 23 21:33:18.277643 2021] [wsgi:error] [pid 15105:tid 140271737095936] [remote ::1:34354] [[9.351187e-03 5.857703e-04 9.900630e-01]]
[Sun May 23 21:33:18.344799 2021] [wsgi:error] [pid 15105:tid 140271737095936] [remote ::1:34354] [[2.0315698e-01 5.8732134e-05 7.9678428e-01]]
[Sun May 23 21:33:18.412658 2021] [wsgi:error] [pid 15105:tid 140271737095936] [remote ::1:34354] [[1.3129169e-01 3.9674775e-04 8.6831158e-01]]
[Sun May 23 21:33:18.492418 2021] [wsgi:error] [pid 15105:tid 140271737095936] [remote ::1:34354] [[0.01497851 0.0282674  0.956754  ]]
[Sun May 23 21:33:18.571990 2021] [wsgi:error] [pid 15105:tid 140271737095936] [remote ::1:34354] [[0.01563484 0.00168601 0.9826791 ]]
[Sun May 23 21:33:18.675171 2021] [wsgi:error] [pid 15105:tid 140271737095936] [remote ::1:34354] [[0.0962153  0.00161867 0.90216607]]
[Sun May 23 21:33:18.740266 2021] [wsgi:error] [pid 15105:tid 140271737095936] [remote ::1:34354] [[0.113419   0.00143218 0.8851489 ]]
[Sun May 23 21:33:18.806527 2021] [wsgi:error] [pid 15105:tid 140271737095936] [remote ::1:34354] [[4.0270045e-01 3.2915789e-04 5.9697032e-01]]
[Sun May 23 21:33:18.875976 2021] [wsgi:error] [pid 15105:tid 140271737095936] [remote ::1:34354] [[0.01356036 0.00146619 0.98497343]]
[Mon May 24 13:45:41.176117 2021] [wsgi:error] [pid 15590:tid 140271762274048] [remote 127.0.0.1:40356] [[0.06033267 0.43878657 0.5008808 ]]
[Mon May 24 13:45:41.360278 2021] [wsgi:error] [pid 15590:tid 140271762274048] [remote 127.0.0.1:40356] [[0.15348502 0.26597616 0.58053887]]
[Mon May 24 13:45:41.509511 2021] [wsgi:error] [pid 15590:tid 140271762274048] [remote 127.0.0.1:40356] [[0.05316162 0.4396888  0.5071496 ]]
[Mon May 24 13:45:41.622478 2021] [wsgi:error] [pid 15590:tid 140271762274048] [remote 127.0.0.1:40356] [[0.0468967  0.17746107 0.7756422 ]]
[Mon May 24 13:45:41.764318 2021] [wsgi:error] [pid 15590:tid 140271762274048] [remote 127.0.0.1:40356] [[0.05424514 0.25499818 0.6907566 ]]
[Mon May 24 13:45:41.917619 2021] [wsgi:error] [pid 15590:tid 140271762274048] [remote 127.0.0.1:40356] [[0.1069025  0.10809644 0.7850011 ]]
[Mon May 24 13:45:42.078593 2021] [wsgi:error] [pid 15590:tid 140271762274048] [remote 127.0.0.1:40356] [[0.08160664 0.17738406 0.74100935]]
[Mon May 24 13:45:42.257845 2021] [wsgi:error] [pid 15590:tid 140271762274048] [remote 127.0.0.1:40356] [[0.10413357 0.1398544  0.756012  ]]
[Mon May 24 13:45:42.392731 2021] [wsgi:error] [pid 15590:tid 140271762274048] [remote 127.0.0.1:40356] [[0.07987671 0.24494149 0.6751818 ]]
[Mon May 24 13:45:42.567194 2021] [wsgi:error] [pid 15590:tid 140271762274048] [remote 127.0.0.1:40356] [[0.03198902 0.02501601 0.94299495]]
[Mon May 24 13:45:42.754649 2021] [wsgi:error] [pid 15590:tid 140271762274048] [remote 127.0.0.1:40356] [[0.04273702 0.01105518 0.94620776]]
[Mon May 24 13:45:42.916667 2021] [wsgi:error] [pid 15590:tid 140271762274048] [remote 127.0.0.1:40356] [[0.05235871 0.00531749 0.9423238 ]]
[Mon May 24 13:45:43.110396 2021] [wsgi:error] [pid 15590:tid 140271762274048] [remote 127.0.0.1:40356] [[0.03841059 0.04669917 0.91489017]]
[Mon May 24 13:45:43.290075 2021] [wsgi:error] [pid 15590:tid 140271762274048] [remote 127.0.0.1:40356] [[0.15871914 0.01438325 0.8268977 ]]
[Mon May 24 13:45:43.459382 2021] [wsgi:error] [pid 15590:tid 140271762274048] [remote 127.0.0.1:40356] [[0.05754692 0.00547559 0.9369775 ]]
[Mon May 24 13:45:43.576961 2021] [wsgi:error] [pid 15590:tid 140271762274048] [remote 127.0.0.1:40356] [[0.11893515 0.01357349 0.8674914 ]]
[Mon May 24 13:45:43.726453 2021] [wsgi:error] [pid 15590:tid 140271762274048] [remote 127.0.0.1:40356] [[0.13301073 0.00610959 0.8608797 ]]
[Mon May 24 13:45:43.918641 2021] [wsgi:error] [pid 15590:tid 140271762274048] [remote 127.0.0.1:40356] [[0.0595872  0.00714392 0.9332689 ]]
[Mon May 24 13:45:44.114460 2021] [wsgi:error] [pid 15590:tid 140271762274048] [remote 127.0.0.1:40356] [[0.08913816 0.00315689 0.90770495]]
[Mon May 24 13:45:44.308959 2021] [wsgi:error] [pid 15590:tid 140271762274048] [remote 127.0.0.1:40356] [[0.17947173 0.00362636 0.8169019 ]]
[Mon May 24 13:45:44.421254 2021] [wsgi:error] [pid 15590:tid 140271762274048] [remote 127.0.0.1:40356] [[1.1394909e-01 8.3726447e-04 8.8521361e-01]]
[Mon May 24 13:45:44.571506 2021] [wsgi:error] [pid 15590:tid 140271762274048] [remote 127.0.0.1:40356] [[0.05004092 0.00138544 0.9485737 ]]
[Mon May 24 13:45:44.720875 2021] [wsgi:error] [pid 15590:tid 140271762274048] [remote 127.0.0.1:40356] [[0.03366191 0.0015757  0.9647624 ]]
[Mon May 24 13:45:44.913662 2021] [wsgi:error] [pid 15590:tid 140271762274048] [remote 127.0.0.1:40356] [[0.03793672 0.00500616 0.95705706]]
[Mon May 24 13:45:45.082729 2021] [wsgi:error] [pid 15590:tid 140271762274048] [remote 127.0.0.1:40356] [[0.02135225 0.01039397 0.9682538 ]]
[Mon May 24 13:45:45.236027 2021] [wsgi:error] [pid 15590:tid 140271762274048] [remote 127.0.0.1:40356] [[0.01733249 0.01037461 0.97229296]]
[Mon May 24 13:45:45.384017 2021] [wsgi:error] [pid 15590:tid 140271762274048] [remote 127.0.0.1:40356] [[0.02067299 0.00639683 0.9729302 ]]
[Mon May 24 13:45:45.519761 2021] [wsgi:error] [pid 15590:tid 140271762274048] [remote 127.0.0.1:40356] [[0.0265251 0.0079432 0.9655317]]
[Mon May 24 13:45:45.634874 2021] [wsgi:error] [pid 15590:tid 140271762274048] [remote 127.0.0.1:40356] [[0.03154146 0.00720354 0.961255  ]]
[Mon May 24 13:45:45.783595 2021] [wsgi:error] [pid 15590:tid 140271762274048] [remote 127.0.0.1:40356] [[0.02193252 0.01819175 0.9598757 ]]
[Mon May 24 13:45:45.930086 2021] [wsgi:error] [pid 15590:tid 140271762274048] [remote 127.0.0.1:40356] [[0.03065391 0.01982398 0.9495221 ]]
[Mon May 24 13:45:46.106763 2021] [wsgi:error] [pid 15590:tid 140271762274048] [remote 127.0.0.1:40356] [[0.01989847 0.01481873 0.96528286]]
[Mon May 24 13:45:46.207795 2021] [wsgi:error] [pid 15590:tid 140271762274048] [remote 127.0.0.1:40356] [[0.03833671 0.01136148 0.9503018 ]]
[Mon May 24 13:45:46.308600 2021] [wsgi:error] [pid 15590:tid 140271762274048] [remote 127.0.0.1:40356] [[0.04982686 0.02152579 0.92864734]]
[Mon May 24 13:45:46.450157 2021] [wsgi:error] [pid 15590:tid 140271762274048] [remote 127.0.0.1:40356] [[0.04246919 0.00992061 0.94761014]]
[Mon May 24 13:45:46.541477 2021] [wsgi:error] [pid 15590:tid 140271762274048] [remote 127.0.0.1:40356] [[0.03597636 0.02093204 0.9430916 ]]
[Mon May 24 13:45:46.687565 2021] [wsgi:error] [pid 15590:tid 140271762274048] [remote 127.0.0.1:40356] [[0.06331074 0.01342092 0.9232683 ]]
[Mon May 24 13:45:46.841526 2021] [wsgi:error] [pid 15590:tid 140271762274048] [remote 127.0.0.1:40356] [[0.19160904 0.04728223 0.76110876]]
[Mon May 24 13:45:47.021657 2021] [wsgi:error] [pid 15590:tid 140271762274048] [remote 127.0.0.1:40356] [[0.08962332 0.02063688 0.88973975]]
[Mon May 24 13:45:47.204277 2021] [wsgi:error] [pid 15590:tid 140271762274048] [remote 127.0.0.1:40356] [[1.1736291e-02 9.5745805e-04 9.8730624e-01]]
[Mon May 24 13:45:47.311329 2021] [wsgi:error] [pid 15590:tid 140271762274048] [remote 127.0.0.1:40356] [[9.1374349e-03 2.7147462e-04 9.9059111e-01]]
[Mon May 24 13:48:29.832831 2021] [wsgi:error] [pid 15590:tid 140271762274048] [remote 127.0.0.1:40372] [[0.07359632 0.48162726 0.4447764 ]]
[Mon May 24 13:48:30.023558 2021] [wsgi:error] [pid 15590:tid 140271762274048] [remote 127.0.0.1:40372] [[0.05971481 0.4533124  0.4869728 ]]
[Mon May 24 13:48:30.191769 2021] [wsgi:error] [pid 15590:tid 140271762274048] [remote 127.0.0.1:40372] [[0.04176266 0.55838764 0.3998497 ]]
[Mon May 24 13:48:30.370994 2021] [wsgi:error] [pid 15590:tid 140271762274048] [remote 127.0.0.1:40372] [[0.07707191 0.285771   0.63715714]]
[Mon May 24 13:48:30.534025 2021] [wsgi:error] [pid 15590:tid 140271762274048] [remote 127.0.0.1:40372] [[0.10415634 0.4811748  0.4146689 ]]
[Mon May 24 13:48:30.627713 2021] [wsgi:error] [pid 15590:tid 140271762274048] [remote 127.0.0.1:40372] [[0.05545456 0.47561154 0.46893394]]
[Mon May 24 13:48:30.757928 2021] [wsgi:error] [pid 15590:tid 140271762274048] [remote 127.0.0.1:40372] [[0.06033267 0.43878657 0.5008808 ]]
[Mon May 24 13:48:30.931982 2021] [wsgi:error] [pid 15590:tid 140271762274048] [remote 127.0.0.1:40372] [[0.15348502 0.26597616 0.58053887]]
[Mon May 24 13:48:31.076767 2021] [wsgi:error] [pid 15590:tid 140271762274048] [remote 127.0.0.1:40372] [[0.05316162 0.4396888  0.5071496 ]]
[Mon May 24 13:48:31.215033 2021] [wsgi:error] [pid 15590:tid 140271762274048] [remote 127.0.0.1:40372] [[0.0468967  0.17746107 0.7756422 ]]
[Mon May 24 13:48:31.314988 2021] [wsgi:error] [pid 15590:tid 140271762274048] [remote 127.0.0.1:40372] [[0.05424514 0.25499818 0.6907566 ]]
[Mon May 24 13:48:31.434245 2021] [wsgi:error] [pid 15590:tid 140271762274048] [remote 127.0.0.1:40372] [[0.1069025  0.10809644 0.7850011 ]]
[Mon May 24 13:48:31.602174 2021] [wsgi:error] [pid 15590:tid 140271762274048] [remote 127.0.0.1:40372] [[0.08160664 0.17738406 0.74100935]]
[Mon May 24 13:48:31.787649 2021] [wsgi:error] [pid 15590:tid 140271762274048] [remote 127.0.0.1:40372] [[0.10413357 0.1398544  0.756012  ]]
[Mon May 24 13:48:31.948692 2021] [wsgi:error] [pid 15590:tid 140271762274048] [remote 127.0.0.1:40372] [[0.07987671 0.24494149 0.6751818 ]]
[Mon May 24 13:48:32.124229 2021] [wsgi:error] [pid 15590:tid 140271762274048] [remote 127.0.0.1:40372] [[0.03198902 0.02501601 0.94299495]]
[Mon May 24 13:48:32.274207 2021] [wsgi:error] [pid 15590:tid 140271762274048] [remote 127.0.0.1:40372] [[0.04273702 0.01105518 0.94620776]]
[Mon May 24 13:48:32.424484 2021] [wsgi:error] [pid 15590:tid 140271762274048] [remote 127.0.0.1:40372] [[0.05235871 0.00531749 0.9423238 ]]
[Mon May 24 13:48:32.562658 2021] [wsgi:error] [pid 15590:tid 140271762274048] [remote 127.0.0.1:40372] [[0.03841059 0.04669917 0.91489017]]
[Mon May 24 13:48:32.676607 2021] [wsgi:error] [pid 15590:tid 140271762274048] [remote 127.0.0.1:40372] [[0.15871914 0.01438325 0.8268977 ]]
[Mon May 24 13:48:32.853008 2021] [wsgi:error] [pid 15590:tid 140271762274048] [remote 127.0.0.1:40372] [[0.05754692 0.00547559 0.9369775 ]]
[Mon May 24 13:48:33.037108 2021] [wsgi:error] [pid 15590:tid 140271762274048] [remote 127.0.0.1:40372] [[0.11893515 0.01357349 0.8674914 ]]
[Mon May 24 13:48:33.190876 2021] [wsgi:error] [pid 15590:tid 140271762274048] [remote 127.0.0.1:40372] [[0.13301073 0.00610959 0.8608797 ]]
[Mon May 24 13:48:33.341081 2021] [wsgi:error] [pid 15590:tid 140271762274048] [remote 127.0.0.1:40372] [[0.0595872  0.00714392 0.9332689 ]]
[Mon May 24 13:48:33.496875 2021] [wsgi:error] [pid 15590:tid 140271762274048] [remote 127.0.0.1:40372] [[0.08913816 0.00315689 0.90770495]]
[Mon May 24 13:48:33.682617 2021] [wsgi:error] [pid 15590:tid 140271762274048] [remote 127.0.0.1:40372] [[0.17947173 0.00362636 0.8169019 ]]
[Mon May 24 13:48:33.805618 2021] [wsgi:error] [pid 15590:tid 140271762274048] [remote 127.0.0.1:40372] [[1.1394909e-01 8.3726447e-04 8.8521361e-01]]
[Mon May 24 13:48:33.941115 2021] [wsgi:error] [pid 15590:tid 140271762274048] [remote 127.0.0.1:40372] [[0.05004092 0.00138544 0.9485737 ]]
[Mon May 24 13:48:34.118697 2021] [wsgi:error] [pid 15590:tid 140271762274048] [remote 127.0.0.1:40372] [[0.03366191 0.0015757  0.9647624 ]]
[Mon May 24 13:48:34.268789 2021] [wsgi:error] [pid 15590:tid 140271762274048] [remote 127.0.0.1:40372] [[0.03793672 0.00500616 0.95705706]]
[Mon May 24 13:48:34.369228 2021] [wsgi:error] [pid 15590:tid 140271762274048] [remote 127.0.0.1:40372] [[0.02135225 0.01039397 0.9682538 ]]
[Mon May 24 13:48:34.494854 2021] [wsgi:error] [pid 15590:tid 140271762274048] [remote 127.0.0.1:40372] [[0.01733249 0.01037461 0.97229296]]
[Mon May 24 13:48:34.674210 2021] [wsgi:error] [pid 15590:tid 140271762274048] [remote 127.0.0.1:40372] [[0.02067299 0.00639683 0.9729302 ]]
[Mon May 24 13:48:34.849700 2021] [wsgi:error] [pid 15590:tid 140271762274048] [remote 127.0.0.1:40372] [[0.0265251 0.0079432 0.9655317]]
[Mon May 24 13:48:34.999777 2021] [wsgi:error] [pid 15590:tid 140271762274048] [remote 127.0.0.1:40372] [[0.03154146 0.00720354 0.961255  ]]
[Mon May 24 13:48:35.144850 2021] [wsgi:error] [pid 15590:tid 140271762274048] [remote 127.0.0.1:40372] [[0.02193252 0.01819175 0.9598757 ]]
[Mon May 24 13:48:35.306489 2021] [wsgi:error] [pid 15590:tid 140271762274048] [remote 127.0.0.1:40372] [[0.03065391 0.01982398 0.9495221 ]]
[Mon May 24 13:48:35.455418 2021] [wsgi:error] [pid 15590:tid 140271762274048] [remote 127.0.0.1:40372] [[0.01989847 0.01481873 0.96528286]]
[Mon May 24 13:48:35.603959 2021] [wsgi:error] [pid 15590:tid 140271762274048] [remote 127.0.0.1:40372] [[0.03833671 0.01136148 0.9503018 ]]
[Mon May 24 13:48:35.767253 2021] [wsgi:error] [pid 15590:tid 140271762274048] [remote 127.0.0.1:40372] [[0.04982686 0.02152579 0.92864734]]
[Mon May 24 13:48:35.934518 2021] [wsgi:error] [pid 15590:tid 140271762274048] [remote 127.0.0.1:40372] [[0.04246919 0.00992061 0.94761014]]
[Mon May 24 13:48:36.085626 2021] [wsgi:error] [pid 15590:tid 140271762274048] [remote 127.0.0.1:40372] [[0.03597636 0.02093204 0.9430916 ]]
[Mon May 24 13:48:36.233756 2021] [wsgi:error] [pid 15590:tid 140271762274048] [remote 127.0.0.1:40372] [[0.06331074 0.01342092 0.9232683 ]]
[Mon May 24 13:48:36.405380 2021] [wsgi:error] [pid 15590:tid 140271762274048] [remote 127.0.0.1:40372] [[0.19160904 0.04728223 0.76110876]]
[Mon May 24 13:48:36.613617 2021] [wsgi:error] [pid 15590:tid 140271762274048] [remote 127.0.0.1:40372] [[0.08962332 0.02063688 0.88973975]]
[Mon May 24 13:48:36.790268 2021] [wsgi:error] [pid 15590:tid 140271762274048] [remote 127.0.0.1:40372] [[1.1736291e-02 9.5745805e-04 9.8730624e-01]]
[Mon May 24 13:48:36.938620 2021] [wsgi:error] [pid 15590:tid 140271762274048] [remote 127.0.0.1:40372] [[9.1374349e-03 2.7147462e-04 9.9059111e-01]]
[Mon May 24 13:48:37.041459 2021] [wsgi:error] [pid 15590:tid 140271762274048] [remote 127.0.0.1:40372] [[7.8492537e-03 1.9257081e-04 9.9195814e-01]]
[Mon May 24 13:52:44.297318 2021] [wsgi:error] [pid 15590:tid 140271762274048] [remote 127.0.0.1:40390] [[0.00133103 0.9904309  0.00823808]]
[Mon May 24 13:52:44.475309 2021] [wsgi:error] [pid 15590:tid 140271762274048] [remote 127.0.0.1:40390] [[1.5795909e-04 9.9980289e-01 3.9235445e-05]]
[Mon May 24 13:52:45.310810 2021] [wsgi:error] [pid 15590:tid 140271762274048] [remote 127.0.0.1:40390] [[0.81935716 0.02542572 0.15521717]]
[Mon May 24 13:52:45.779198 2021] [wsgi:error] [pid 15590:tid 140271762274048] [remote 127.0.0.1:40390] [[0.05298957 0.05394964 0.89306074]]
[Mon May 24 13:52:46.038710 2021] [wsgi:error] [pid 15590:tid 140271762274048] [remote 127.0.0.1:40390] [[0.3536204  0.16194174 0.48443788]]
[Mon May 24 13:52:46.220862 2021] [wsgi:error] [pid 15590:tid 140271762274048] [remote 127.0.0.1:40390] [[0.02014444 0.09795111 0.8819044 ]]
[Mon May 24 13:52:46.445968 2021] [wsgi:error] [pid 15590:tid 140271762274048] [remote 127.0.0.1:40390] [[0.08207241 0.01927609 0.8986515 ]]
[Mon May 24 13:52:47.152099 2021] [wsgi:error] [pid 15590:tid 140271762274048] [remote 127.0.0.1:40390] [[0.6559453  0.14138968 0.20266508]]
[Mon May 24 13:52:47.465528 2021] [wsgi:error] [pid 15590:tid 140271762274048] [remote 127.0.0.1:40390] [[0.01185075 0.8386999  0.14944942]]
[Mon May 24 13:52:47.602527 2021] [wsgi:error] [pid 15590:tid 140271762274048] [remote 127.0.0.1:40390] [[0.19649622 0.77737623 0.02612749]]
[Mon May 24 13:52:47.781919 2021] [wsgi:error] [pid 15590:tid 140271762274048] [remote 127.0.0.1:40390] [[6.2947808e-04 9.5453954e-01 4.4831004e-02]]
[Mon May 24 13:52:47.924859 2021] [wsgi:error] [pid 15590:tid 140271762274048] [remote 127.0.0.1:40390] [[0.00304696 0.9834019  0.01355113]]
[Mon May 24 13:52:48.085325 2021] [wsgi:error] [pid 15590:tid 140271762274048] [remote 127.0.0.1:40390] [[0.14470795 0.07293891 0.78235316]]
[Mon May 24 13:52:48.303610 2021] [wsgi:error] [pid 15590:tid 140271762274048] [remote 127.0.0.1:40390] [[0.05724773 0.08278081 0.85997146]]
[Mon May 24 13:52:48.574371 2021] [wsgi:error] [pid 15590:tid 140271762274048] [remote 127.0.0.1:40390] [[0.08381362 0.15408841 0.762098  ]]
[Mon May 24 13:52:48.766356 2021] [wsgi:error] [pid 15590:tid 140271762274048] [remote 127.0.0.1:40390] [[4.8896135e-04 9.9938118e-01 1.2990444e-04]]
[Mon May 24 13:52:49.018450 2021] [wsgi:error] [pid 15590:tid 140271762274048] [remote 127.0.0.1:40390] [[7.1820548e-05 9.8496026e-01 1.4967860e-02]]
[Mon May 24 13:52:49.229319 2021] [wsgi:error] [pid 15590:tid 140271762274048] [remote 127.0.0.1:40390] [[0.18070154 0.3674345  0.4518639 ]]
[Mon May 24 13:52:49.402436 2021] [wsgi:error] [pid 15590:tid 140271762274048] [remote 127.0.0.1:40390] [[0.9630765  0.00125515 0.03566829]]
[Mon May 24 13:52:49.566677 2021] [wsgi:error] [pid 15590:tid 140271762274048] [remote 127.0.0.1:40390] [[0.85868895 0.10707364 0.03423736]]
[Mon May 24 13:52:49.689658 2021] [wsgi:error] [pid 15590:tid 140271762274048] [remote 127.0.0.1:40390] [[5.7745439e-01 3.0335694e-04 4.2224225e-01]]
[Mon May 24 13:52:49.817073 2021] [wsgi:error] [pid 15590:tid 140271762274048] [remote 127.0.0.1:40390] [[0.07738202 0.16504306 0.757575  ]]
[Mon May 24 13:52:50.100305 2021] [wsgi:error] [pid 15590:tid 140271762274048] [remote 127.0.0.1:40390] [[0.23754948 0.12680948 0.63564104]]
[Mon May 24 13:52:50.467530 2021] [wsgi:error] [pid 15590:tid 140271762274048] [remote 127.0.0.1:40390] [[0.3312302  0.19494718 0.47382262]]
[Mon May 24 13:52:50.689231 2021] [wsgi:error] [pid 15590:tid 140271762274048] [remote 127.0.0.1:40390] [[0.19868417 0.00738313 0.7939327 ]]
[Mon May 24 13:52:50.898717 2021] [wsgi:error] [pid 15590:tid 140271762274048] [remote 127.0.0.1:40390] [[0.00494788 0.92786455 0.06718753]]
[Mon May 24 13:52:51.200346 2021] [wsgi:error] [pid 15590:tid 140271762274048] [remote 127.0.0.1:40390] [[0.01427636 0.95729744 0.02842623]]
[Mon May 24 13:52:51.339309 2021] [wsgi:error] [pid 15590:tid 140271762274048] [remote 127.0.0.1:40390] [[0.0037982  0.9769653  0.01923648]]
[Mon May 24 13:52:51.554109 2021] [wsgi:error] [pid 15590:tid 140271762274048] [remote 127.0.0.1:40390] [[6.9167358e-01 2.1544260e-04 3.0811098e-01]]
[Mon May 24 13:52:51.703300 2021] [wsgi:error] [pid 15590:tid 140271762274048] [remote 127.0.0.1:40390] [[2.5975265e-04 9.7358501e-01 2.6155287e-02]]
[Mon May 24 13:52:51.810252 2021] [wsgi:error] [pid 15590:tid 140271762274048] [remote 127.0.0.1:40390] [[6.9045752e-01 1.3819437e-05 3.0952865e-01]]
[Mon May 24 13:52:51.956285 2021] [wsgi:error] [pid 15590:tid 140271762274048] [remote 127.0.0.1:40390] [[0.02512098 0.4221083  0.5527707 ]]
[Mon May 24 13:52:52.188706 2021] [wsgi:error] [pid 15590:tid 140271762274048] [remote 127.0.0.1:40390] [[0.09197168 0.00582861 0.90219975]]
[Mon May 24 13:52:52.447743 2021] [wsgi:error] [pid 15590:tid 140271762274048] [remote 127.0.0.1:40390] [[0.03084692 0.03632134 0.93283176]]
[Mon May 24 13:52:52.662608 2021] [wsgi:error] [pid 15590:tid 140271762274048] [remote 127.0.0.1:40390] [[1.11432135e-01 3.85329658e-05 8.88529301e-01]]
[Mon May 24 13:52:52.836115 2021] [wsgi:error] [pid 15590:tid 140271762274048] [remote 127.0.0.1:40390] [[0.00109156 0.9550079  0.04390059]]
[Mon May 24 13:52:53.026435 2021] [wsgi:error] [pid 15590:tid 140271762274048] [remote 127.0.0.1:40390] [[0.11116685 0.75182974 0.13700339]]
[Mon May 24 13:52:53.218394 2021] [wsgi:error] [pid 15590:tid 140271762274048] [remote 127.0.0.1:40390] [[0.06077296 0.02152784 0.9176992 ]]
[Mon May 24 13:52:53.407042 2021] [wsgi:error] [pid 15590:tid 140271762274048] [remote 127.0.0.1:40390] [[0.12869713 0.5003494  0.3709534 ]]
[Mon May 24 13:52:53.606011 2021] [wsgi:error] [pid 15590:tid 140271762274048] [remote 127.0.0.1:40390] [[0.0021333  0.8731732  0.12469344]]
[Mon May 24 13:52:53.841799 2021] [wsgi:error] [pid 15590:tid 140271762274048] [remote 127.0.0.1:40390] [[0.00146493 0.9947483  0.00378671]]
[Mon May 24 13:52:55.137604 2021] [wsgi:error] [pid 15590:tid 140271762274048] [remote 127.0.0.1:40390] [[0.35431805 0.5035731  0.1421088 ]]
[Mon May 24 13:52:55.742809 2021] [wsgi:error] [pid 15590:tid 140271762274048] [remote 127.0.0.1:40390] [[0.34307835 0.22152448 0.4353972 ]]
[Mon May 24 13:52:55.927469 2021] [wsgi:error] [pid 15590:tid 140271762274048] [remote 127.0.0.1:40390] [[0.00936861 0.9678326  0.02279871]]
[Mon May 24 13:52:56.136438 2021] [wsgi:error] [pid 15590:tid 140271762274048] [remote 127.0.0.1:40390] [[0.00373474 0.7700581  0.22620712]]
[Mon May 24 13:52:56.307344 2021] [wsgi:error] [pid 15590:tid 140271762274048] [remote 127.0.0.1:40390] [[4.2993391e-01 4.5999698e-04 5.6960613e-01]]
[Mon May 24 13:52:56.467919 2021] [wsgi:error] [pid 15590:tid 140271762274048] [remote 127.0.0.1:40390] [[0.5843541  0.12212394 0.29352197]]
[Mon May 24 13:52:56.629574 2021] [wsgi:error] [pid 15590:tid 140271762274048] [remote 127.0.0.1:40390] [[0.00607903 0.9889243  0.00499664]]
[Mon May 24 13:52:56.773118 2021] [wsgi:error] [pid 15590:tid 140271762274048] [remote 127.0.0.1:40390] [[0.17623304 0.15020104 0.6735659 ]]
[Mon May 24 13:52:56.963747 2021] [wsgi:error] [pid 15590:tid 140271762274048] [remote 127.0.0.1:40390] [[0.78439933 0.12885217 0.08674849]]
[Mon May 24 13:52:57.822463 2021] [wsgi:error] [pid 15590:tid 140271762274048] [remote 127.0.0.1:40390] [[0.7436507  0.16968407 0.08666528]]
[Mon May 24 13:52:58.149195 2021] [wsgi:error] [pid 15590:tid 140271762274048] [remote 127.0.0.1:40390] [[0.22997062 0.00801475 0.7620147 ]]
[Mon May 24 13:52:58.357550 2021] [wsgi:error] [pid 15590:tid 140271762274048] [remote 127.0.0.1:40390] [[0.3778941  0.08677593 0.53532994]]
[Mon May 24 13:52:58.502078 2021] [wsgi:error] [pid 15590:tid 140271762274048] [remote 127.0.0.1:40390] [[2.7240004e-02 1.2966592e-04 9.7263032e-01]]
[Mon May 24 13:52:58.719755 2021] [wsgi:error] [pid 15590:tid 140271762274048] [remote 127.0.0.1:40390] [[0.39572868 0.4342049  0.17006639]]
[Mon May 24 13:52:59.048319 2021] [wsgi:error] [pid 15590:tid 140271762274048] [remote 127.0.0.1:40390] [[0.8866827  0.06201111 0.05130622]]
[Mon May 24 13:52:59.466422 2021] [wsgi:error] [pid 15590:tid 140271762274048] [remote 127.0.0.1:40390] [[0.68677914 0.00102054 0.3122004 ]]
[Mon May 24 13:52:59.711651 2021] [wsgi:error] [pid 15590:tid 140271762274048] [remote 127.0.0.1:40390] [[0.19797868 0.7524837  0.04953764]]
[Mon May 24 13:52:59.875836 2021] [wsgi:error] [pid 15590:tid 140271762274048] [remote 127.0.0.1:40390] [[0.00800807 0.9759576  0.01603442]]
[Mon May 24 13:53:00.049990 2021] [wsgi:error] [pid 15590:tid 140271762274048] [remote 127.0.0.1:40390] [[0.00080092 0.6491899  0.35000917]]
[Mon May 24 13:53:00.211284 2021] [wsgi:error] [pid 15590:tid 140271762274048] [remote 127.0.0.1:40390] [[0.35380492 0.4143093  0.23188585]]
[Mon May 24 13:53:00.321508 2021] [wsgi:error] [pid 15590:tid 140271762274048] [remote 127.0.0.1:40390] [[0.00471956 0.97581756 0.01946283]]
[Mon May 24 13:53:00.484523 2021] [wsgi:error] [pid 15590:tid 140271762274048] [remote 127.0.0.1:40390] [[0.23885648 0.06947627 0.69166726]]
[Mon May 24 13:53:00.701260 2021] [wsgi:error] [pid 15590:tid 140271762274048] [remote 127.0.0.1:40390] [[0.02577504 0.79143196 0.18279296]]
[Mon May 24 13:53:00.862902 2021] [wsgi:error] [pid 15590:tid 140271762274048] [remote 127.0.0.1:40390] [[2.32799083e-01 1.12779264e-04 7.67088115e-01]]
[Mon May 24 13:53:01.014031 2021] [wsgi:error] [pid 15590:tid 140271762274048] [remote 127.0.0.1:40390] [[0.29018557 0.6742254  0.03558903]]
[Mon May 24 13:53:01.233615 2021] [wsgi:error] [pid 15590:tid 140271762274048] [remote 127.0.0.1:40390] [[0.5202862 0.3051097 0.174604 ]]
[Mon May 24 13:53:01.433105 2021] [wsgi:error] [pid 15590:tid 140271762274048] [remote 127.0.0.1:40390] [[0.0265594  0.9508044  0.02263616]]
[Mon May 24 13:53:01.632322 2021] [wsgi:error] [pid 15590:tid 140271762274048] [remote 127.0.0.1:40390] [[0.0265594  0.9508044  0.02263616]]
[Mon May 24 13:53:01.797117 2021] [wsgi:error] [pid 15590:tid 140271762274048] [remote 127.0.0.1:40390] [[0.06807838 0.1751638  0.75675786]]
[Mon May 24 13:53:02.017926 2021] [wsgi:error] [pid 15590:tid 140271762274048] [remote 127.0.0.1:40390] [[0.07189776 0.5253526  0.40274966]]
[Mon May 24 13:53:02.283774 2021] [wsgi:error] [pid 15590:tid 140271762274048] [remote 127.0.0.1:40390] [[0.70087063 0.09308573 0.20604365]]
[Mon May 24 13:53:02.473833 2021] [wsgi:error] [pid 15590:tid 140271762274048] [remote 127.0.0.1:40390] [[0.01436537 0.24538113 0.7402535 ]]
[Mon May 24 13:53:02.660909 2021] [wsgi:error] [pid 15590:tid 140271762274048] [remote 127.0.0.1:40390] [[0.0028891  0.84559596 0.15151489]]
[Mon May 24 13:53:02.851594 2021] [wsgi:error] [pid 15590:tid 140271762274048] [remote 127.0.0.1:40390] [[0.0293283  0.9006622  0.07000951]]
[Mon May 24 13:53:03.004981 2021] [wsgi:error] [pid 15590:tid 140271762274048] [remote 127.0.0.1:40390] [[0.0115508 0.785177  0.2032723]]
[Mon May 24 13:53:03.195214 2021] [wsgi:error] [pid 15590:tid 140271762274048] [remote 127.0.0.1:40390] [[0.4864186  0.00893678 0.50464463]]
[Mon May 24 13:53:03.326393 2021] [wsgi:error] [pid 15590:tid 140271762274048] [remote 127.0.0.1:40390] [[0.00349557 0.9866263  0.00987809]]
[Mon May 24 13:53:03.495328 2021] [wsgi:error] [pid 15590:tid 140271762274048] [remote 127.0.0.1:40390] [[0.01822982 0.484488   0.4972822 ]]
[Mon May 24 13:53:03.631483 2021] [wsgi:error] [pid 15590:tid 140271762274048] [remote 127.0.0.1:40390] [[0.00106306 0.993404   0.00553293]]
[Mon May 24 13:53:03.747919 2021] [wsgi:error] [pid 15590:tid 140271762274048] [remote 127.0.0.1:40390] [[0.03211727 0.05776221 0.9101205 ]]
[Mon May 24 13:53:04.365247 2021] [wsgi:error] [pid 15590:tid 140271762274048] [remote 127.0.0.1:40390] [[0.614951   0.10008162 0.2849674 ]]
[Mon May 24 13:53:04.724385 2021] [wsgi:error] [pid 15590:tid 140271762274048] [remote 127.0.0.1:40390] [[0.6453123  0.02873943 0.3259483 ]]
[Mon May 24 13:53:04.956274 2021] [wsgi:error] [pid 15590:tid 140271762274048] [remote 127.0.0.1:40390] [[9.825862e-04 9.948137e-01 4.203658e-03]]
[Mon May 24 13:53:05.127983 2021] [wsgi:error] [pid 15590:tid 140271762274048] [remote 127.0.0.1:40390] [[0.03469466 0.00172343 0.9635819 ]]
[Mon May 24 13:53:05.431686 2021] [wsgi:error] [pid 15590:tid 140271762274048] [remote 127.0.0.1:40390] [[0.04449891 0.39834285 0.55715823]]
[Mon May 24 13:53:05.640682 2021] [wsgi:error] [pid 15590:tid 140271762274048] [remote 127.0.0.1:40390] [[6.9930160e-01 9.1290174e-05 3.0060709e-01]]
[Mon May 24 13:53:05.829231 2021] [wsgi:error] [pid 15590:tid 140271762274048] [remote 127.0.0.1:40390] [[8.6445099e-01 6.2603655e-04 1.3492297e-01]]
[Mon May 24 13:53:06.068322 2021] [wsgi:error] [pid 15590:tid 140271762274048] [remote 127.0.0.1:40390] [[3.3919682e-04 9.9624121e-01 3.4196381e-03]]
[Mon May 24 13:53:06.287035 2021] [wsgi:error] [pid 15590:tid 140271762274048] [remote 127.0.0.1:40390] [[0.28772008 0.07448289 0.63779706]]
[Mon May 24 13:53:06.541329 2021] [wsgi:error] [pid 15590:tid 140271762274048] [remote 127.0.0.1:40390] [[0.00226697 0.93596363 0.06176937]]
[Mon May 24 13:53:06.798036 2021] [wsgi:error] [pid 15590:tid 140271762274048] [remote 127.0.0.1:40390] [[1.9375359e-01 3.8248245e-04 8.0586398e-01]]
[Mon May 24 13:53:07.024044 2021] [wsgi:error] [pid 15590:tid 140271762274048] [remote 127.0.0.1:40390] [[5.7608038e-01 2.2882735e-04 4.2369077e-01]]
[Mon May 24 13:53:07.266667 2021] [wsgi:error] [pid 15590:tid 140271762274048] [remote 127.0.0.1:40390] [[0.14235136 0.10266991 0.7549787 ]]
[Mon May 24 13:53:07.386061 2021] [wsgi:error] [pid 15590:tid 140271762274048] [remote 127.0.0.1:40390] [[0.00806103 0.9749543  0.0169847 ]]
[Mon May 24 13:53:07.586246 2021] [wsgi:error] [pid 15590:tid 140271762274048] [remote 127.0.0.1:40390] [[0.02253088 0.88682455 0.09064463]]
2021-05-23 22:02:15.701143: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2021-05-23 22:02:15.701164: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2021-05-24 13:45:22.819667: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2021-05-24 13:45:22.819899: W tensorflow/stream_executor/cuda/cuda_driver.cc:326] failed call to cuInit: UNKNOWN ERROR (303)
2021-05-24 13:45:22.819969: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (DESKTOP-MNQ7F8E): /proc/driver/nvidia/version does not exist
2021-05-24 13:45:22.822390: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2021-05-24 13:45:24.590811: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:176] None of the MLIR Optimization Passes are enabled (registered 2)
2021-05-24 13:45:24.594404: I tensorflow/core/platform/profile_utils/cpu_utils.cc:114] CPU Frequency: 1991995000 Hz
2021-05-24 14:03:44.333891: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2021-05-24 14:03:44.333946: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2021-05-24 15:12:45.289120: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2021-05-24 15:12:45.289197: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2021-05-24 15:19:24.818830: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2021-05-24 15:19:24.818903: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2021-05-24 15:22:38.487810: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2021-05-24 15:22:38.487849: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2021-05-24 15:33:31.180671: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2021-05-24 15:33:31.180750: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2021-05-24 15:36:49.477668: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2021-05-24 15:36:49.477698: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2021-05-24 15:38:58.945889: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2021-05-24 15:38:58.945922: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2021-05-24 16:07:54.793267: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2021-05-24 16:07:54.793297: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2021-05-24 16:25:24.603485: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2021-05-24 16:25:24.603515: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2021-05-24 16:32:57.416574: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2021-05-24 16:32:57.416594: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2021-05-24 16:42:40.611210: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2021-05-24 16:42:40.611229: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2021-05-24 16:50:19.446524: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2021-05-24 16:50:19.446545: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
[Mon May 24 17:01:17.416249 2021] [wsgi:error] [pid 19770:tid 140677575370496] [remote ::1:34560] [[9.6297739e-03 9.1982674e-04 9.8945040e-01]]
[Mon May 24 17:01:17.471887 2021] [wsgi:error] [pid 19770:tid 140677575370496] [remote ::1:34560] [[0.02050695 0.06258767 0.9169054 ]]
2021-05-24 17:00:56.077236: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2021-05-24 17:00:56.077256: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2021-05-24 17:01:06.918199: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2021-05-24 17:01:06.918218: W tensorflow/stream_executor/cuda/cuda_driver.cc:326] failed call to cuInit: UNKNOWN ERROR (303)
2021-05-24 17:01:06.918234: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (DESKTOP-MNQ7F8E): /proc/driver/nvidia/version does not exist
2021-05-24 17:01:06.918420: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2021-05-24 17:01:07.642103: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:176] None of the MLIR Optimization Passes are enabled (registered 2)
2021-05-24 17:01:07.642763: I tensorflow/core/platform/profile_utils/cpu_utils.cc:114] CPU Frequency: 1991995000 Hz
2021-05-24 17:08:33.649616: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2021-05-24 17:08:33.649634: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2021-05-24 17:40:05.196042: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2021-05-24 17:40:05.196063: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2021-05-24 17:43:53.870454: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2021-05-24 17:43:53.870474: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2021-05-24 17:53:48.642424: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2021-05-24 17:53:48.642443: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2021-05-24 17:54:22.386350: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2021-05-24 17:54:22.386372: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
[Mon May 24 17:58:50.648704 2021] [wsgi:error] [pid 20614:tid 139737512314624] [remote ::1:34626] [[0.02591931 0.00367296 0.9704077 ]]
[Mon May 24 17:58:50.722901 2021] [wsgi:error] [pid 20614:tid 139737512314624] [remote ::1:34626] [[0.00273046 0.0191434  0.9781261 ]]
2021-05-24 17:58:28.316797: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2021-05-24 17:58:28.316816: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2021-05-24 17:58:41.306793: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2021-05-24 17:58:41.306811: W tensorflow/stream_executor/cuda/cuda_driver.cc:326] failed call to cuInit: UNKNOWN ERROR (303)
2021-05-24 17:58:41.306826: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (DESKTOP-MNQ7F8E): /proc/driver/nvidia/version does not exist
2021-05-24 17:58:41.306990: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2021-05-24 17:58:41.881976: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:176] None of the MLIR Optimization Passes are enabled (registered 2)
2021-05-24 17:58:41.882274: I tensorflow/core/platform/profile_utils/cpu_utils.cc:114] CPU Frequency: 1991995000 Hz
2021-05-24 18:02:11.200044: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2021-05-24 18:02:11.200063: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2021-05-24 18:06:42.235443: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2021-05-24 18:06:42.235463: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
[Mon May 24 18:11:29.754379 2021] [wsgi:error] [pid 21050:tid 140222881351424] [remote ::1:34658] [[9.6297739e-03 9.1982674e-04 9.8945040e-01]]
[Mon May 24 18:11:29.806770 2021] [wsgi:error] [pid 21050:tid 140222881351424] [remote ::1:34658] [[0.02050695 0.06258767 0.9169054 ]]
[Mon May 24 18:11:29.863774 2021] [wsgi:error] [pid 21050:tid 140222881351424] [remote ::1:34658] [[0.1561424  0.00467606 0.83918154]]
[Mon May 24 18:11:29.925151 2021] [wsgi:error] [pid 21050:tid 140222881351424] [remote ::1:34658] [[0.00845459 0.00888204 0.9826634 ]]
[Mon May 24 18:11:29.984334 2021] [wsgi:error] [pid 21050:tid 140222881351424] [remote ::1:34658] [[4.597729e-02 3.666400e-04 9.536561e-01]]
[Mon May 24 18:11:30.057966 2021] [wsgi:error] [pid 21050:tid 140222881351424] [remote ::1:34658] [[0.02591931 0.00367296 0.9704077 ]]
[Mon May 24 18:11:30.125252 2021] [wsgi:error] [pid 21050:tid 140222881351424] [remote ::1:34658] [[0.00273046 0.0191434  0.9781261 ]]
[Mon May 24 18:11:30.226981 2021] [wsgi:error] [pid 21050:tid 140222881351424] [remote ::1:34658] [[0.05130138 0.00247891 0.94621974]]
[Mon May 24 18:11:30.297073 2021] [wsgi:error] [pid 21050:tid 140222881351424] [remote ::1:34658] [[0.0045835  0.00117963 0.9942368 ]]
[Mon May 24 18:11:30.368850 2021] [wsgi:error] [pid 21050:tid 140222881351424] [remote ::1:34658] [[4.8797271e-01 3.9616763e-04 5.1163113e-01]]
[Mon May 24 18:11:30.438896 2021] [wsgi:error] [pid 21050:tid 140222881351424] [remote ::1:34658] [[6.1493507e-03 6.6049478e-04 9.9319011e-01]]
[Mon May 24 18:11:30.506283 2021] [wsgi:error] [pid 21050:tid 140222881351424] [remote ::1:34658] [[7.2099008e-02 2.0876895e-04 9.2769223e-01]]
[Mon May 24 18:11:30.571725 2021] [wsgi:error] [pid 21050:tid 140222881351424] [remote ::1:34658] [[0.0311581  0.01410805 0.9547339 ]]
[Mon May 24 18:11:30.631647 2021] [wsgi:error] [pid 21050:tid 140222881351424] [remote ::1:34658] [[4.3041032e-02 1.7129301e-04 9.5678765e-01]]
[Mon May 24 18:11:30.727303 2021] [wsgi:error] [pid 21050:tid 140222881351424] [remote ::1:34658] [[0.19477195 0.00555172 0.79967636]]
[Mon May 24 18:11:30.798989 2021] [wsgi:error] [pid 21050:tid 140222881351424] [remote ::1:34658] [[0.0181159  0.00715475 0.9747293 ]]
[Mon May 24 18:11:30.867187 2021] [wsgi:error] [pid 21050:tid 140222881351424] [remote ::1:34658] [[0.00215236 0.14575163 0.85209596]]
[Mon May 24 18:11:30.941176 2021] [wsgi:error] [pid 21050:tid 140222881351424] [remote ::1:34658] [[0.01975805 0.00176907 0.9784728 ]]
[Mon May 24 18:11:31.010447 2021] [wsgi:error] [pid 21050:tid 140222881351424] [remote ::1:34658] [[1.5929326e-01 6.4941193e-04 8.4005737e-01]]
2021-05-24 18:10:11.196688: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2021-05-24 18:10:11.196709: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2021-05-24 18:11:20.678012: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2021-05-24 18:11:20.678038: W tensorflow/stream_executor/cuda/cuda_driver.cc:326] failed call to cuInit: UNKNOWN ERROR (303)
2021-05-24 18:11:20.678057: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (DESKTOP-MNQ7F8E): /proc/driver/nvidia/version does not exist
2021-05-24 18:11:20.678266: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2021-05-24 18:11:21.317642: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:176] None of the MLIR Optimization Passes are enabled (registered 2)
2021-05-24 18:11:21.318008: I tensorflow/core/platform/profile_utils/cpu_utils.cc:114] CPU Frequency: 1991995000 Hz
2021-05-24 18:21:21.883271: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2021-05-24 18:21:21.883290: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2021-05-24 18:31:22.326711: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2021-05-24 18:31:22.326730: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
[Mon May 24 18:52:18.371146 2021] [wsgi:error] [pid 21549:tid 139840979461888] [remote ::1:34680] [[9.6297739e-03 9.1982674e-04 9.8945040e-01]]
[Mon May 24 18:52:18.425894 2021] [wsgi:error] [pid 21549:tid 139840979461888] [remote ::1:34680] [[0.02050695 0.06258767 0.9169054 ]]
[Mon May 24 18:52:18.491386 2021] [wsgi:error] [pid 21549:tid 139840979461888] [remote ::1:34680] [[0.1561424  0.00467606 0.83918154]]
[Mon May 24 18:53:00.009338 2021] [wsgi:error] [pid 21549:tid 139840996247296] [remote ::1:34692] [[9.6297739e-03 9.1982674e-04 9.8945040e-01]]
[Mon May 24 18:53:00.072422 2021] [wsgi:error] [pid 21549:tid 139840996247296] [remote ::1:34692] [[0.02050695 0.06258767 0.9169054 ]]
[Mon May 24 18:53:00.153465 2021] [wsgi:error] [pid 21549:tid 139840996247296] [remote ::1:34692] [[0.1561424  0.00467606 0.83918154]]
[Mon May 24 18:53:00.235598 2021] [wsgi:error] [pid 21549:tid 139840996247296] [remote ::1:34692] [[0.02591931 0.00367296 0.9704077 ]]
[Mon May 24 18:53:00.308248 2021] [wsgi:error] [pid 21549:tid 139840996247296] [remote ::1:34692] [[0.00273046 0.0191434  0.9781261 ]]
2021-05-24 18:51:57.303104: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2021-05-24 18:51:57.303123: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2021-05-24 18:52:08.717203: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2021-05-24 18:52:08.717226: W tensorflow/stream_executor/cuda/cuda_driver.cc:326] failed call to cuInit: UNKNOWN ERROR (303)
2021-05-24 18:52:08.717242: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (DESKTOP-MNQ7F8E): /proc/driver/nvidia/version does not exist
2021-05-24 18:52:08.717566: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2021-05-24 18:52:09.395020: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:176] None of the MLIR Optimization Passes are enabled (registered 2)
2021-05-24 18:52:09.395319: I tensorflow/core/platform/profile_utils/cpu_utils.cc:114] CPU Frequency: 1991995000 Hz
[Mon May 24 18:54:38.025659 2021] [wsgi:error] [pid 21741:tid 140332394387200] [remote ::1:34704] [2021-05-24 18:54:38,023] ERROR in app: Exception on /multi_upload_gan [POST]
[Mon May 24 18:54:38.025689 2021] [wsgi:error] [pid 21741:tid 140332394387200] [remote ::1:34704] Traceback (most recent call last):
[Mon May 24 18:54:38.025693 2021] [wsgi:error] [pid 21741:tid 140332394387200] [remote ::1:34704]   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2051, in wsgi_app
[Mon May 24 18:54:38.025697 2021] [wsgi:error] [pid 21741:tid 140332394387200] [remote ::1:34704]     response = self.full_dispatch_request()
[Mon May 24 18:54:38.025700 2021] [wsgi:error] [pid 21741:tid 140332394387200] [remote ::1:34704]   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1501, in full_dispatch_request
[Mon May 24 18:54:38.025703 2021] [wsgi:error] [pid 21741:tid 140332394387200] [remote ::1:34704]     rv = self.handle_user_exception(e)
[Mon May 24 18:54:38.025706 2021] [wsgi:error] [pid 21741:tid 140332394387200] [remote ::1:34704]   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1499, in full_dispatch_request
[Mon May 24 18:54:38.025709 2021] [wsgi:error] [pid 21741:tid 140332394387200] [remote ::1:34704]     rv = self.dispatch_request()
[Mon May 24 18:54:38.025712 2021] [wsgi:error] [pid 21741:tid 140332394387200] [remote ::1:34704]   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1485, in dispatch_request
[Mon May 24 18:54:38.025715 2021] [wsgi:error] [pid 21741:tid 140332394387200] [remote ::1:34704]     return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
[Mon May 24 18:54:38.025718 2021] [wsgi:error] [pid 21741:tid 140332394387200] [remote ::1:34704]   File "/home/copes/graduation-project/Web/app.py", line 30, in multi_upload_gan
[Mon May 24 18:54:38.025721 2021] [wsgi:error] [pid 21741:tid 140332394387200] [remote ::1:34704]     file.save("home/copes/graduation-project/Web/static/GAN/{}.jpg".format(IDX))
[Mon May 24 18:54:38.025724 2021] [wsgi:error] [pid 21741:tid 140332394387200] [remote ::1:34704]   File "/usr/local/lib/python3.8/dist-packages/werkzeug/datastructures.py", line 3013, in save
[Mon May 24 18:54:38.025728 2021] [wsgi:error] [pid 21741:tid 140332394387200] [remote ::1:34704]     dst = open(dst, "wb")
[Mon May 24 18:54:38.025737 2021] [wsgi:error] [pid 21741:tid 140332394387200] [remote ::1:34704] PermissionError: [Errno 13] Permission denied: 'home/copes/graduation-project/Web/static/GAN/0.jpg'
[Mon May 24 18:54:44.774488 2021] [wsgi:error] [pid 21741:tid 140332427958016] [remote ::1:34706] [2021-05-24 18:54:44,774] ERROR in app: Exception on /multi_upload_gan [POST]
[Mon May 24 18:54:44.774507 2021] [wsgi:error] [pid 21741:tid 140332427958016] [remote ::1:34706] Traceback (most recent call last):
[Mon May 24 18:54:44.774510 2021] [wsgi:error] [pid 21741:tid 140332427958016] [remote ::1:34706]   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2051, in wsgi_app
[Mon May 24 18:54:44.774513 2021] [wsgi:error] [pid 21741:tid 140332427958016] [remote ::1:34706]     response = self.full_dispatch_request()
[Mon May 24 18:54:44.774515 2021] [wsgi:error] [pid 21741:tid 140332427958016] [remote ::1:34706]   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1501, in full_dispatch_request
[Mon May 24 18:54:44.774517 2021] [wsgi:error] [pid 21741:tid 140332427958016] [remote ::1:34706]     rv = self.handle_user_exception(e)
[Mon May 24 18:54:44.774519 2021] [wsgi:error] [pid 21741:tid 140332427958016] [remote ::1:34706]   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1499, in full_dispatch_request
[Mon May 24 18:54:44.774521 2021] [wsgi:error] [pid 21741:tid 140332427958016] [remote ::1:34706]     rv = self.dispatch_request()
[Mon May 24 18:54:44.774523 2021] [wsgi:error] [pid 21741:tid 140332427958016] [remote ::1:34706]   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1485, in dispatch_request
[Mon May 24 18:54:44.774526 2021] [wsgi:error] [pid 21741:tid 140332427958016] [remote ::1:34706]     return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
[Mon May 24 18:54:44.774528 2021] [wsgi:error] [pid 21741:tid 140332427958016] [remote ::1:34706]   File "/home/copes/graduation-project/Web/app.py", line 30, in multi_upload_gan
[Mon May 24 18:54:44.774530 2021] [wsgi:error] [pid 21741:tid 140332427958016] [remote ::1:34706]     file.save("home/copes/graduation-project/Web/static/GAN/{}.jpg".format(IDX))
[Mon May 24 18:54:44.774532 2021] [wsgi:error] [pid 21741:tid 140332427958016] [remote ::1:34706]   File "/usr/local/lib/python3.8/dist-packages/werkzeug/datastructures.py", line 3013, in save
[Mon May 24 18:54:44.774534 2021] [wsgi:error] [pid 21741:tid 140332427958016] [remote ::1:34706]     dst = open(dst, "wb")
[Mon May 24 18:54:44.774536 2021] [wsgi:error] [pid 21741:tid 140332427958016] [remote ::1:34706] PermissionError: [Errno 13] Permission denied: 'home/copes/graduation-project/Web/static/GAN/0.jpg'
[Mon May 24 18:54:56.525131 2021] [wsgi:error] [pid 21741:tid 140332394387200] [remote ::1:34708] [2021-05-24 18:54:56,524] ERROR in app: Exception on /multi_upload_gan [POST]
[Mon May 24 18:54:56.525152 2021] [wsgi:error] [pid 21741:tid 140332394387200] [remote ::1:34708] Traceback (most recent call last):
[Mon May 24 18:54:56.525155 2021] [wsgi:error] [pid 21741:tid 140332394387200] [remote ::1:34708]   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2051, in wsgi_app
[Mon May 24 18:54:56.525158 2021] [wsgi:error] [pid 21741:tid 140332394387200] [remote ::1:34708]     response = self.full_dispatch_request()
[Mon May 24 18:54:56.525160 2021] [wsgi:error] [pid 21741:tid 140332394387200] [remote ::1:34708]   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1501, in full_dispatch_request
[Mon May 24 18:54:56.525162 2021] [wsgi:error] [pid 21741:tid 140332394387200] [remote ::1:34708]     rv = self.handle_user_exception(e)
[Mon May 24 18:54:56.525164 2021] [wsgi:error] [pid 21741:tid 140332394387200] [remote ::1:34708]   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1499, in full_dispatch_request
[Mon May 24 18:54:56.525167 2021] [wsgi:error] [pid 21741:tid 140332394387200] [remote ::1:34708]     rv = self.dispatch_request()
[Mon May 24 18:54:56.525169 2021] [wsgi:error] [pid 21741:tid 140332394387200] [remote ::1:34708]   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1485, in dispatch_request
[Mon May 24 18:54:56.525178 2021] [wsgi:error] [pid 21741:tid 140332394387200] [remote ::1:34708]     return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
[Mon May 24 18:54:56.525180 2021] [wsgi:error] [pid 21741:tid 140332394387200] [remote ::1:34708]   File "/home/copes/graduation-project/Web/app.py", line 30, in multi_upload_gan
[Mon May 24 18:54:56.525183 2021] [wsgi:error] [pid 21741:tid 140332394387200] [remote ::1:34708]     file.save("home/copes/graduation-project/Web/static/GAN/{}.jpg".format(IDX))
[Mon May 24 18:54:56.525185 2021] [wsgi:error] [pid 21741:tid 140332394387200] [remote ::1:34708]   File "/usr/local/lib/python3.8/dist-packages/werkzeug/datastructures.py", line 3013, in save
[Mon May 24 18:54:56.525188 2021] [wsgi:error] [pid 21741:tid 140332394387200] [remote ::1:34708]     dst = open(dst, "wb")
[Mon May 24 18:54:56.525191 2021] [wsgi:error] [pid 21741:tid 140332394387200] [remote ::1:34708] PermissionError: [Errno 13] Permission denied: 'home/copes/graduation-project/Web/static/GAN/0.jpg'
2021-05-24 18:54:30.358978: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2021-05-24 18:54:30.359008: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
[Mon May 24 19:15:05.701533 2021] [wsgi:error] [pid 21886:tid 140021940127488] [remote ::1:34720] [[9.6297739e-03 9.1982674e-04 9.8945040e-01]]
[Mon May 24 19:15:05.754417 2021] [wsgi:error] [pid 21886:tid 140021940127488] [remote ::1:34720] [[0.02050695 0.06258767 0.9169054 ]]
[Mon May 24 19:15:05.811046 2021] [wsgi:error] [pid 21886:tid 140021940127488] [remote ::1:34720] [[0.1561424  0.00467606 0.83918154]]
[Mon May 24 19:15:05.877618 2021] [wsgi:error] [pid 21886:tid 140021940127488] [remote ::1:34720] [[0.00845459 0.00888204 0.9826634 ]]
[Mon May 24 19:15:05.936777 2021] [wsgi:error] [pid 21886:tid 140021940127488] [remote ::1:34720] [[4.597729e-02 3.666400e-04 9.536561e-01]]
[Mon May 24 19:15:06.011084 2021] [wsgi:error] [pid 21886:tid 140021940127488] [remote ::1:34720] [[0.02591931 0.00367296 0.9704077 ]]
[Mon May 24 19:15:06.084267 2021] [wsgi:error] [pid 21886:tid 140021940127488] [remote ::1:34720] [[0.00273046 0.0191434  0.9781261 ]]
[Mon May 24 19:15:06.180325 2021] [wsgi:error] [pid 21886:tid 140021940127488] [remote ::1:34720] [[0.05130138 0.00247891 0.94621974]]
[Mon May 24 19:15:06.256110 2021] [wsgi:error] [pid 21886:tid 140021940127488] [remote ::1:34720] [[0.0045835  0.00117963 0.9942368 ]]
[Mon May 24 19:15:06.327524 2021] [wsgi:error] [pid 21886:tid 140021940127488] [remote ::1:34720] [[4.8797271e-01 3.9616763e-04 5.1163113e-01]]
[Mon May 24 19:15:06.400532 2021] [wsgi:error] [pid 21886:tid 140021940127488] [remote ::1:34720] [[6.1493507e-03 6.6049478e-04 9.9319011e-01]]
[Mon May 24 19:15:06.467295 2021] [wsgi:error] [pid 21886:tid 140021940127488] [remote ::1:34720] [[7.2099008e-02 2.0876895e-04 9.2769223e-01]]
[Mon May 24 19:15:06.538584 2021] [wsgi:error] [pid 21886:tid 140021940127488] [remote ::1:34720] [[0.0311581  0.01410805 0.9547339 ]]
[Mon May 24 19:15:06.604055 2021] [wsgi:error] [pid 21886:tid 140021940127488] [remote ::1:34720] [[4.3041032e-02 1.7129301e-04 9.5678765e-01]]
[Mon May 24 19:15:06.698230 2021] [wsgi:error] [pid 21886:tid 140021940127488] [remote ::1:34720] [[0.19477195 0.00555172 0.79967636]]
[Mon May 24 19:15:06.768558 2021] [wsgi:error] [pid 21886:tid 140021940127488] [remote ::1:34720] [[0.0181159  0.00715475 0.9747293 ]]
[Mon May 24 19:15:06.840533 2021] [wsgi:error] [pid 21886:tid 140021940127488] [remote ::1:34720] [[0.00215236 0.14575163 0.85209596]]
[Mon May 24 19:15:06.914120 2021] [wsgi:error] [pid 21886:tid 140021940127488] [remote ::1:34720] [[0.01975805 0.00176907 0.9784728 ]]
[Mon May 24 19:15:06.985227 2021] [wsgi:error] [pid 21886:tid 140021940127488] [remote ::1:34720] [[1.5929326e-01 6.4941193e-04 8.4005737e-01]]
[Mon May 24 19:15:07.056753 2021] [wsgi:error] [pid 21886:tid 140021940127488] [remote ::1:34720] [[0.10447256 0.00173842 0.89378893]]
[Mon May 24 19:15:07.120752 2021] [wsgi:error] [pid 21886:tid 140021940127488] [remote ::1:34720] [[1.9839752e-02 3.9648614e-04 9.7976375e-01]]
[Mon May 24 19:15:07.189488 2021] [wsgi:error] [pid 21886:tid 140021940127488] [remote ::1:34720] [[4.0209842e-01 5.7689834e-04 5.9732479e-01]]
[Mon May 24 19:15:07.266218 2021] [wsgi:error] [pid 21886:tid 140021940127488] [remote ::1:34720] [[0.1287375  0.0066506  0.86461186]]
[Mon May 24 19:15:07.338688 2021] [wsgi:error] [pid 21886:tid 140021940127488] [remote ::1:34720] [[1.8442921e-02 3.1668242e-05 9.8152542e-01]]
[Mon May 24 19:15:07.417939 2021] [wsgi:error] [pid 21886:tid 140021940127488] [remote ::1:34720] [[0.11244605 0.03096933 0.85658467]]
[Mon May 24 19:15:07.487780 2021] [wsgi:error] [pid 21886:tid 140021940127488] [remote ::1:34720] [[0.31806996 0.00182547 0.68010455]]
[Mon May 24 19:15:07.559556 2021] [wsgi:error] [pid 21886:tid 140021940127488] [remote ::1:34720] [[1.0387175e-01 6.4992596e-04 8.9547831e-01]]
[Mon May 24 19:15:07.629419 2021] [wsgi:error] [pid 21886:tid 140021940127488] [remote ::1:34720] [[1.4036876e-01 2.9067480e-04 8.5934049e-01]]
[Mon May 24 19:15:07.697693 2021] [wsgi:error] [pid 21886:tid 140021940127488] [remote ::1:34720] [[0.03275191 0.08921272 0.8780354 ]]
[Mon May 24 19:15:07.758781 2021] [wsgi:error] [pid 21886:tid 140021940127488] [remote ::1:34720] [[0.11591227 0.00254197 0.8815458 ]]
[Mon May 24 19:15:07.827217 2021] [wsgi:error] [pid 21886:tid 140021940127488] [remote ::1:34720] [[0.13894767 0.2243983  0.6366541 ]]
[Mon May 24 19:15:07.902001 2021] [wsgi:error] [pid 21886:tid 140021940127488] [remote ::1:34720] [[0.00771133 0.00438042 0.9879083 ]]
[Mon May 24 19:15:07.976994 2021] [wsgi:error] [pid 21886:tid 140021940127488] [remote ::1:34720] [[5.4134727e-02 1.4948583e-04 9.4571579e-01]]
[Mon May 24 19:15:08.049233 2021] [wsgi:error] [pid 21886:tid 140021940127488] [remote ::1:34720] [[0.00515046 0.137072   0.85777754]]
[Mon May 24 19:15:08.126188 2021] [wsgi:error] [pid 21886:tid 140021940127488] [remote ::1:34720] [[0.02074791 0.01212754 0.9671245 ]]
[Mon May 24 19:15:08.197962 2021] [wsgi:error] [pid 21886:tid 140021940127488] [remote ::1:34720] [[0.00525339 0.02359281 0.9711538 ]]
[Mon May 24 19:15:08.262077 2021] [wsgi:error] [pid 21886:tid 140021940127488] [remote ::1:34720] [[0.0428966  0.03135791 0.9257454 ]]
[Mon May 24 19:15:08.326907 2021] [wsgi:error] [pid 21886:tid 140021940127488] [remote ::1:34720] [[0.3347329  0.10236973 0.56289744]]
[Mon May 24 19:15:08.459440 2021] [wsgi:error] [pid 21886:tid 140021940127488] [remote ::1:34720] [[1.2683483e-02 2.6598462e-04 9.8705053e-01]]
[Mon May 24 19:15:08.529178 2021] [wsgi:error] [pid 21886:tid 140021940127488] [remote ::1:34720] [[9.351187e-03 5.857703e-04 9.900630e-01]]
[Mon May 24 19:15:08.596461 2021] [wsgi:error] [pid 21886:tid 140021940127488] [remote ::1:34720] [[2.0315698e-01 5.8732134e-05 7.9678428e-01]]
[Mon May 24 19:15:34.399324 2021] [wsgi:error] [pid 21886:tid 140021965305600] [remote ::1:34728] [[9.6297739e-03 9.1982674e-04 9.8945040e-01]]
[Mon May 24 19:15:34.462224 2021] [wsgi:error] [pid 21886:tid 140021965305600] [remote ::1:34728] [[0.02050695 0.06258767 0.9169054 ]]
[Mon May 24 19:15:34.543908 2021] [wsgi:error] [pid 21886:tid 140021965305600] [remote ::1:34728] [[0.1561424  0.00467606 0.83918154]]
[Mon May 24 19:15:34.620789 2021] [wsgi:error] [pid 21886:tid 140021965305600] [remote ::1:34728] [[0.00845459 0.00888204 0.9826634 ]]
[Mon May 24 19:15:34.692955 2021] [wsgi:error] [pid 21886:tid 140021965305600] [remote ::1:34728] [[4.597729e-02 3.666400e-04 9.536561e-01]]
[Mon May 24 19:15:34.781437 2021] [wsgi:error] [pid 21886:tid 140021965305600] [remote ::1:34728] [[0.02591931 0.00367296 0.9704077 ]]
[Mon May 24 19:15:34.857477 2021] [wsgi:error] [pid 21886:tid 140021965305600] [remote ::1:34728] [[0.00273046 0.0191434  0.9781261 ]]
[Mon May 24 19:15:34.969316 2021] [wsgi:error] [pid 21886:tid 140021965305600] [remote ::1:34728] [[0.05130138 0.00247891 0.94621974]]
[Mon May 24 19:15:35.045600 2021] [wsgi:error] [pid 21886:tid 140021965305600] [remote ::1:34728] [[0.0045835  0.00117963 0.9942368 ]]
[Mon May 24 19:15:35.127100 2021] [wsgi:error] [pid 21886:tid 140021965305600] [remote ::1:34728] [[4.8797271e-01 3.9616763e-04 5.1163113e-01]]
[Mon May 24 19:15:35.215754 2021] [wsgi:error] [pid 21886:tid 140021965305600] [remote ::1:34728] [[6.1493507e-03 6.6049478e-04 9.9319011e-01]]
[Mon May 24 19:15:35.304037 2021] [wsgi:error] [pid 21886:tid 140021965305600] [remote ::1:34728] [[7.2099008e-02 2.0876895e-04 9.2769223e-01]]
[Mon May 24 19:15:35.382616 2021] [wsgi:error] [pid 21886:tid 140021965305600] [remote ::1:34728] [[0.0311581  0.01410805 0.9547339 ]]
[Mon May 24 19:15:35.449511 2021] [wsgi:error] [pid 21886:tid 140021965305600] [remote ::1:34728] [[4.3041032e-02 1.7129301e-04 9.5678765e-01]]
[Mon May 24 19:15:35.544518 2021] [wsgi:error] [pid 21886:tid 140021965305600] [remote ::1:34728] [[0.19477195 0.00555172 0.79967636]]
[Mon May 24 19:15:35.617913 2021] [wsgi:error] [pid 21886:tid 140021965305600] [remote ::1:34728] [[0.0181159  0.00715475 0.9747293 ]]
[Mon May 24 19:15:35.687452 2021] [wsgi:error] [pid 21886:tid 140021965305600] [remote ::1:34728] [[0.00215236 0.14575163 0.85209596]]
[Mon May 24 19:15:35.760258 2021] [wsgi:error] [pid 21886:tid 140021965305600] [remote ::1:34728] [[0.01975805 0.00176907 0.9784728 ]]
[Mon May 24 19:15:35.833014 2021] [wsgi:error] [pid 21886:tid 140021965305600] [remote ::1:34728] [[1.5929326e-01 6.4941193e-04 8.4005737e-01]]
[Mon May 24 19:15:53.386905 2021] [wsgi:error] [pid 21886:tid 140021931734784] [remote ::1:34738] [[1.2683483e-02 2.6598462e-04 9.8705053e-01]]
[Mon May 24 19:15:53.457174 2021] [wsgi:error] [pid 21886:tid 140021931734784] [remote ::1:34738] [[9.351187e-03 5.857703e-04 9.900630e-01]]
[Mon May 24 19:15:53.528793 2021] [wsgi:error] [pid 21886:tid 140021931734784] [remote ::1:34738] [[2.0315698e-01 5.8732134e-05 7.9678428e-01]]
[Mon May 24 19:15:53.600618 2021] [wsgi:error] [pid 21886:tid 140021931734784] [remote ::1:34738] [[1.3129169e-01 3.9674775e-04 8.6831158e-01]]
[Mon May 24 19:15:53.678765 2021] [wsgi:error] [pid 21886:tid 140021931734784] [remote ::1:34738] [[0.01497851 0.0282674  0.956754  ]]
[Mon May 24 19:15:53.757473 2021] [wsgi:error] [pid 21886:tid 140021931734784] [remote ::1:34738] [[0.01563484 0.00168601 0.9826791 ]]
[Mon May 24 19:15:53.859326 2021] [wsgi:error] [pid 21886:tid 140021931734784] [remote ::1:34738] [[0.0962153  0.00161867 0.90216607]]
[Mon May 24 19:15:53.926580 2021] [wsgi:error] [pid 21886:tid 140021931734784] [remote ::1:34738] [[0.113419   0.00143218 0.8851489 ]]
[Mon May 24 19:15:53.996273 2021] [wsgi:error] [pid 21886:tid 140021931734784] [remote ::1:34738] [[4.0270045e-01 3.2915789e-04 5.9697032e-01]]
[Mon May 24 19:15:54.071947 2021] [wsgi:error] [pid 21886:tid 140021931734784] [remote ::1:34738] [[0.01356036 0.00146619 0.98497343]]
[Mon May 24 19:15:54.136718 2021] [wsgi:error] [pid 21886:tid 140021931734784] [remote ::1:34738] [[0.10555577 0.00237805 0.89206624]]
[Mon May 24 19:15:54.204432 2021] [wsgi:error] [pid 21886:tid 140021931734784] [remote ::1:34738] [[0.0390755  0.00220466 0.95871985]]
[Mon May 24 19:15:54.278122 2021] [wsgi:error] [pid 21886:tid 140021931734784] [remote ::1:34738] [[0.3756094  0.00065641 0.6237342 ]]
[Mon May 24 19:15:54.343824 2021] [wsgi:error] [pid 21886:tid 140021931734784] [remote ::1:34738] [[0.23184894 0.01046115 0.75768995]]
[Mon May 24 19:15:54.411715 2021] [wsgi:error] [pid 21886:tid 140021931734784] [remote ::1:34738] [[0.05170992 0.04311773 0.90517235]]
[Mon May 24 19:15:54.483525 2021] [wsgi:error] [pid 21886:tid 140021931734784] [remote ::1:34738] [[0.06273152 0.00819713 0.9290714 ]]
[Mon May 24 19:15:54.549905 2021] [wsgi:error] [pid 21886:tid 140021931734784] [remote ::1:34738] [[0.00867269 0.00710053 0.98422676]]
[Mon May 24 19:15:54.616810 2021] [wsgi:error] [pid 21886:tid 140021931734784] [remote ::1:34738] [[0.16794285 0.00228982 0.8297674 ]]
[Mon May 24 19:15:54.680970 2021] [wsgi:error] [pid 21886:tid 140021931734784] [remote ::1:34738] [[0.10094725 0.00250942 0.8965433 ]]
[Mon May 24 19:15:54.783190 2021] [wsgi:error] [pid 21886:tid 140021931734784] [remote ::1:34738] [[4.0272083e-02 6.9289043e-04 9.5903498e-01]]
[Mon May 24 19:15:54.911927 2021] [wsgi:error] [pid 21886:tid 140021931734784] [remote ::1:34738] [[0.02371016 0.0180021  0.9582877 ]]
[Mon May 24 19:15:54.998331 2021] [wsgi:error] [pid 21886:tid 140021931734784] [remote ::1:34738] [[0.03014618 0.00453822 0.9653156 ]]
2021-05-24 19:07:07.280756: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2021-05-24 19:07:07.280776: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2021-05-24 19:14:56.324536: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2021-05-24 19:14:56.324557: W tensorflow/stream_executor/cuda/cuda_driver.cc:326] failed call to cuInit: UNKNOWN ERROR (303)
2021-05-24 19:14:56.324571: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (DESKTOP-MNQ7F8E): /proc/driver/nvidia/version does not exist
2021-05-24 19:14:56.324737: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2021-05-24 19:14:57.004975: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:176] None of the MLIR Optimization Passes are enabled (registered 2)
2021-05-24 19:14:57.005332: I tensorflow/core/platform/profile_utils/cpu_utils.cc:114] CPU Frequency: 1991995000 Hz
2021-05-24 19:18:38.309282: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2021-05-24 19:18:38.309301: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2021-05-24 19:20:14.858241: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2021-05-24 19:20:14.858263: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
[Mon May 24 19:27:28.851525 2021] [wsgi:error] [pid 22579:tid 139778483988224] [remote ::1:34768] [2021-05-24 19:27:28,850] ERROR in app: Exception on /multi_upload_gan [POST]
[Mon May 24 19:27:28.851596 2021] [wsgi:error] [pid 22579:tid 139778483988224] [remote ::1:34768] Traceback (most recent call last):
[Mon May 24 19:27:28.851602 2021] [wsgi:error] [pid 22579:tid 139778483988224] [remote ::1:34768]   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2051, in wsgi_app
[Mon May 24 19:27:28.851606 2021] [wsgi:error] [pid 22579:tid 139778483988224] [remote ::1:34768]     response = self.full_dispatch_request()
[Mon May 24 19:27:28.851610 2021] [wsgi:error] [pid 22579:tid 139778483988224] [remote ::1:34768]   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1501, in full_dispatch_request
[Mon May 24 19:27:28.851613 2021] [wsgi:error] [pid 22579:tid 139778483988224] [remote ::1:34768]     rv = self.handle_user_exception(e)
[Mon May 24 19:27:28.851617 2021] [wsgi:error] [pid 22579:tid 139778483988224] [remote ::1:34768]   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1499, in full_dispatch_request
[Mon May 24 19:27:28.851626 2021] [wsgi:error] [pid 22579:tid 139778483988224] [remote ::1:34768]     rv = self.dispatch_request()
[Mon May 24 19:27:28.851629 2021] [wsgi:error] [pid 22579:tid 139778483988224] [remote ::1:34768]   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1485, in dispatch_request
[Mon May 24 19:27:28.851632 2021] [wsgi:error] [pid 22579:tid 139778483988224] [remote ::1:34768]     return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
[Mon May 24 19:27:28.851635 2021] [wsgi:error] [pid 22579:tid 139778483988224] [remote ::1:34768]   File "/home/copes/graduation-project/Web/app.py", line 30, in multi_upload_gan
[Mon May 24 19:27:28.851638 2021] [wsgi:error] [pid 22579:tid 139778483988224] [remote ::1:34768]     file.save("home/copes/graduation-project/Web/static/GAN/{}.jpg".format(IDX))
[Mon May 24 19:27:28.851643 2021] [wsgi:error] [pid 22579:tid 139778483988224] [remote ::1:34768]   File "/usr/local/lib/python3.8/dist-packages/werkzeug/datastructures.py", line 3013, in save
[Mon May 24 19:27:28.851647 2021] [wsgi:error] [pid 22579:tid 139778483988224] [remote ::1:34768]     dst = open(dst, "wb")
[Mon May 24 19:27:28.851651 2021] [wsgi:error] [pid 22579:tid 139778483988224] [remote ::1:34768] PermissionError: [Errno 13] Permission denied: 'home/copes/graduation-project/Web/static/GAN/0.jpg'
2021-05-24 19:23:12.825103: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2021-05-24 19:23:12.825122: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2021-05-24 19:34:20.881262: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2021-05-24 19:34:20.881282: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2021-05-24 20:27:40.680828: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2021-05-24 20:27:40.680874: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2021-05-24 20:30:12.329158: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2021-05-24 20:30:12.329178: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2021-05-24 20:32:18.977044: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2021-05-24 20:32:18.977066: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
[Mon May 24 21:01:01.606173 2021] [wsgi:error] [pid 23340:tid 140329124136704] [remote ::1:34796] [[9.6297739e-03 9.1982674e-04 9.8945040e-01]]
[Mon May 24 21:01:01.994532 2021] [wsgi:error] [pid 23340:tid 140329124136704] [remote ::1:34796] [[0.02050695 0.06258767 0.9169054 ]]
[Mon May 24 21:01:02.945595 2021] [wsgi:error] [pid 23340:tid 140329124136704] [remote ::1:34796] [[0.1561424  0.00467606 0.83918154]]
[Mon May 24 21:01:04.615124 2021] [wsgi:error] [pid 23340:tid 140329115744000] [remote ::1:34798] [[9.6297739e-03 9.1982674e-04 9.8945040e-01]]
[Mon May 24 21:01:04.809508 2021] [wsgi:error] [pid 23340:tid 140329115744000] [remote ::1:34798] [[0.02050695 0.06258767 0.9169054 ]]
[Mon May 24 21:01:04.989157 2021] [wsgi:error] [pid 23340:tid 140329115744000] [remote ::1:34798] [[0.1561424  0.00467606 0.83918154]]
2021-05-24 21:00:23.808541: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2021-05-24 21:00:23.808572: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2021-05-24 21:00:35.617629: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2021-05-24 21:00:35.617653: W tensorflow/stream_executor/cuda/cuda_driver.cc:326] failed call to cuInit: UNKNOWN ERROR (303)
2021-05-24 21:00:35.617677: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (DESKTOP-MNQ7F8E): /proc/driver/nvidia/version does not exist
2021-05-24 21:00:35.617902: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2021-05-24 21:00:37.051342: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:176] None of the MLIR Optimization Passes are enabled (registered 2)
2021-05-24 21:00:37.052410: I tensorflow/core/platform/profile_utils/cpu_utils.cc:114] CPU Frequency: 1991995000 Hz
2021-05-24 21:06:03.708160: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2021-05-24 21:06:03.708204: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2021-05-24 21:10:24.422795: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2021-05-24 21:10:24.422944: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2021-05-24 21:18:36.710200: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2021-05-24 21:18:36.710244: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
[Mon May 24 21:30:45.849906 2021] [wsgi:error] [pid 24049:tid 140033488463616] [remote ::1:34844] [[9.6297739e-03 9.1982674e-04 9.8945040e-01]]
[Mon May 24 21:30:45.850982 2021] [wsgi:error] [pid 24049:tid 140033480070912] [remote ::1:34846] [[9.6297739e-03 9.1982674e-04 9.8945040e-01]]
[Mon May 24 21:30:46.118497 2021] [wsgi:error] [pid 24049:tid 140033488463616] [remote ::1:34844] [[0.02050695 0.06258767 0.9169054 ]]
[Mon May 24 21:30:46.141794 2021] [wsgi:error] [pid 24049:tid 140033480070912] [remote ::1:34846] [[0.02050695 0.06258767 0.9169054 ]]
[Mon May 24 21:30:46.442991 2021] [wsgi:error] [pid 24049:tid 140033480070912] [remote ::1:34846] [[0.1561424  0.00467606 0.83918154]]
[Mon May 24 21:30:46.466573 2021] [wsgi:error] [pid 24049:tid 140033488463616] [remote ::1:34844] [[0.1561424  0.00467606 0.83918154]]
[Mon May 24 21:30:46.680978 2021] [wsgi:error] [pid 24049:tid 140033480070912] [remote ::1:34846] [[0.00845459 0.00888204 0.9826634 ]]
[Mon May 24 21:30:46.745500 2021] [wsgi:error] [pid 24049:tid 140033488463616] [remote ::1:34844] [[0.00845459 0.00888204 0.9826634 ]]
[Mon May 24 21:30:46.886498 2021] [wsgi:error] [pid 24049:tid 140033480070912] [remote ::1:34846] [[4.597729e-02 3.666400e-04 9.536561e-01]]
[Mon May 24 21:30:47.037819 2021] [wsgi:error] [pid 24049:tid 140033488463616] [remote ::1:34844] [[4.597729e-02 3.666400e-04 9.536561e-01]]
[Mon May 24 21:30:47.197350 2021] [wsgi:error] [pid 24049:tid 140033480070912] [remote ::1:34846] [[0.02591931 0.00367296 0.9704077 ]]
[Mon May 24 21:30:47.376115 2021] [wsgi:error] [pid 24049:tid 140033488463616] [remote ::1:34844] [[0.02591931 0.00367296 0.9704077 ]]
[Mon May 24 21:30:47.496579 2021] [wsgi:error] [pid 24049:tid 140033480070912] [remote ::1:34846] [[0.00273046 0.0191434  0.9781261 ]]
[Mon May 24 21:30:47.673118 2021] [wsgi:error] [pid 24049:tid 140033488463616] [remote ::1:34844] [[0.00273046 0.0191434  0.9781261 ]]
[Mon May 24 21:30:47.910991 2021] [wsgi:error] [pid 24049:tid 140033480070912] [remote ::1:34846] [[0.05130138 0.00247891 0.94621974]]
[Mon May 24 21:30:48.093053 2021] [wsgi:error] [pid 24049:tid 140033488463616] [remote ::1:34844] [[0.05130138 0.00247891 0.94621974]]
[Mon May 24 21:30:48.172826 2021] [wsgi:error] [pid 24049:tid 140033480070912] [remote ::1:34846] [[0.0045835  0.00117963 0.9942368 ]]
[Mon May 24 21:30:48.438549 2021] [wsgi:error] [pid 24049:tid 140033488463616] [remote ::1:34844] [[0.0045835  0.00117963 0.9942368 ]]
[Mon May 24 21:30:48.525689 2021] [wsgi:error] [pid 24049:tid 140033480070912] [remote ::1:34846] [[4.8797271e-01 3.9616763e-04 5.1163113e-01]]
[Mon May 24 21:30:48.689573 2021] [wsgi:error] [pid 24049:tid 140033488463616] [remote ::1:34844] [[4.8797271e-01 3.9616763e-04 5.1163113e-01]]
[Mon May 24 21:30:48.722326 2021] [wsgi:error] [pid 24049:tid 140033480070912] [remote ::1:34846] [[6.1493507e-03 6.6049478e-04 9.9319011e-01]]
[Mon May 24 21:30:48.863133 2021] [wsgi:error] [pid 24049:tid 140033488463616] [remote ::1:34844] [[6.1493507e-03 6.6049478e-04 9.9319011e-01]]
[Mon May 24 21:30:48.945315 2021] [wsgi:error] [pid 24049:tid 140033480070912] [remote ::1:34846] [[7.2099008e-02 2.0876895e-04 9.2769223e-01]]
[Mon May 24 21:30:49.076068 2021] [wsgi:error] [pid 24049:tid 140033488463616] [remote ::1:34844] [[7.2099008e-02 2.0876895e-04 9.2769223e-01]]
[Mon May 24 21:30:49.115327 2021] [wsgi:error] [pid 24049:tid 140033480070912] [remote ::1:34846] [[0.0311581  0.01410805 0.9547339 ]]
[Mon May 24 21:30:49.222163 2021] [wsgi:error] [pid 24049:tid 140033488463616] [remote ::1:34844] [[0.0311581  0.01410805 0.9547339 ]]
[Mon May 24 21:30:49.245995 2021] [wsgi:error] [pid 24049:tid 140033480070912] [remote ::1:34846] [[4.3041032e-02 1.7129301e-04 9.5678765e-01]]
[Mon May 24 21:30:49.427333 2021] [wsgi:error] [pid 24049:tid 140033488463616] [remote ::1:34844] [[4.3041032e-02 1.7129301e-04 9.5678765e-01]]
[Mon May 24 21:30:49.640543 2021] [wsgi:error] [pid 24049:tid 140033480070912] [remote ::1:34846] [[0.19477195 0.00555172 0.79967636]]
[Mon May 24 21:30:49.833974 2021] [wsgi:error] [pid 24049:tid 140033488463616] [remote ::1:34844] [[0.19477195 0.00555172 0.79967636]]
[Mon May 24 21:30:49.914187 2021] [wsgi:error] [pid 24049:tid 140033480070912] [remote ::1:34846] [[0.0181159  0.00715475 0.9747293 ]]
[Mon May 24 21:30:50.122473 2021] [wsgi:error] [pid 24049:tid 140033488463616] [remote ::1:34844] [[0.0181159  0.00715475 0.9747293 ]]
[Mon May 24 21:30:50.217031 2021] [wsgi:error] [pid 24049:tid 140033480070912] [remote ::1:34846] [[0.00215236 0.14575163 0.85209596]]
[Mon May 24 21:30:50.463491 2021] [wsgi:error] [pid 24049:tid 140033488463616] [remote ::1:34844] [[0.00215236 0.14575163 0.85209596]]
[Mon May 24 21:30:50.531849 2021] [wsgi:error] [pid 24049:tid 140033480070912] [remote ::1:34846] [[0.01975805 0.00176907 0.9784728 ]]
[Mon May 24 21:30:50.810861 2021] [wsgi:error] [pid 24049:tid 140033488463616] [remote ::1:34844] [[0.01975805 0.00176907 0.9784728 ]]
[Mon May 24 21:30:50.871219 2021] [wsgi:error] [pid 24049:tid 140033480070912] [remote ::1:34846] [[1.5929326e-01 6.4941193e-04 8.4005737e-01]]
[Mon May 24 21:30:51.168759 2021] [wsgi:error] [pid 24049:tid 140033488463616] [remote ::1:34844] [[1.5929326e-01 6.4941193e-04 8.4005737e-01]]
[Mon May 24 21:30:51.209225 2021] [wsgi:error] [pid 24049:tid 140033480070912] [remote ::1:34846] [[0.10447256 0.00173842 0.89378893]]
[Mon May 24 21:30:51.563011 2021] [wsgi:error] [pid 24049:tid 140033480070912] [remote ::1:34846] [[1.9839752e-02 3.9648614e-04 9.7976375e-01]]
[Mon May 24 21:30:51.576206 2021] [wsgi:error] [pid 24049:tid 140033488463616] [remote ::1:34844] [[0.10447256 0.00173842 0.89378893]]
[Mon May 24 21:30:51.732773 2021] [wsgi:error] [pid 24049:tid 140033480070912] [remote ::1:34846] [[4.0209842e-01 5.7689834e-04 5.9732479e-01]]
[Mon May 24 21:30:51.751723 2021] [wsgi:error] [pid 24049:tid 140033488463616] [remote ::1:34844] [[1.9839752e-02 3.9648614e-04 9.7976375e-01]]
[Mon May 24 21:30:51.904207 2021] [wsgi:error] [pid 24049:tid 140033480070912] [remote ::1:34846] [[0.1287375  0.0066506  0.86461186]]
[Mon May 24 21:30:51.954898 2021] [wsgi:error] [pid 24049:tid 140033488463616] [remote ::1:34844] [[4.0209842e-01 5.7689834e-04 5.9732479e-01]]
[Mon May 24 21:30:52.269611 2021] [wsgi:error] [pid 24049:tid 140033480070912] [remote ::1:34846] [[1.8442921e-02 3.1668242e-05 9.8152542e-01]]
[Mon May 24 21:30:52.304494 2021] [wsgi:error] [pid 24049:tid 140033488463616] [remote ::1:34844] [[0.1287375  0.0066506  0.86461186]]
[Mon May 24 21:30:52.528982 2021] [wsgi:error] [pid 24049:tid 140033480070912] [remote ::1:34846] [[0.11244605 0.03096933 0.85658467]]
[Mon May 24 21:30:52.581761 2021] [wsgi:error] [pid 24049:tid 140033488463616] [remote ::1:34844] [[1.8442921e-02 3.1668242e-05 9.8152542e-01]]
[Mon May 24 21:30:52.719302 2021] [wsgi:error] [pid 24049:tid 140033480070912] [remote ::1:34846] [[0.31806996 0.00182547 0.68010455]]
[Mon May 24 21:30:52.785814 2021] [wsgi:error] [pid 24049:tid 140033488463616] [remote ::1:34844] [[0.11244605 0.03096933 0.85658467]]
[Mon May 24 21:30:52.905872 2021] [wsgi:error] [pid 24049:tid 140033480070912] [remote ::1:34846] [[1.0387175e-01 6.4992596e-04 8.9547831e-01]]
[Mon May 24 21:30:52.971735 2021] [wsgi:error] [pid 24049:tid 140033488463616] [remote ::1:34844] [[0.31806996 0.00182547 0.68010455]]
[Mon May 24 21:30:53.092194 2021] [wsgi:error] [pid 24049:tid 140033480070912] [remote ::1:34846] [[1.4036876e-01 2.9067480e-04 8.5934049e-01]]
[Mon May 24 21:30:53.155193 2021] [wsgi:error] [pid 24049:tid 140033488463616] [remote ::1:34844] [[1.0387175e-01 6.4992596e-04 8.9547831e-01]]
[Mon May 24 21:30:53.288249 2021] [wsgi:error] [pid 24049:tid 140033480070912] [remote ::1:34846] [[0.03275191 0.08921272 0.8780354 ]]
[Mon May 24 21:30:53.356540 2021] [wsgi:error] [pid 24049:tid 140033488463616] [remote ::1:34844] [[1.4036876e-01 2.9067480e-04 8.5934049e-01]]
[Mon May 24 21:30:53.518160 2021] [wsgi:error] [pid 24049:tid 140033480070912] [remote ::1:34846] [[0.11591227 0.00254197 0.8815458 ]]
[Mon May 24 21:30:53.600758 2021] [wsgi:error] [pid 24049:tid 140033488463616] [remote ::1:34844] [[0.03275191 0.08921272 0.8780354 ]]
[Mon May 24 21:30:53.833994 2021] [wsgi:error] [pid 24049:tid 140033480070912] [remote ::1:34846] [[0.13894767 0.2243983  0.6366541 ]]
[Mon May 24 21:30:53.898939 2021] [wsgi:error] [pid 24049:tid 140033488463616] [remote ::1:34844] [[0.11591227 0.00254197 0.8815458 ]]
[Mon May 24 21:30:54.245041 2021] [wsgi:error] [pid 24049:tid 140033480070912] [remote ::1:34846] [[0.00771133 0.00438042 0.9879083 ]]
[Mon May 24 21:30:54.254871 2021] [wsgi:error] [pid 24049:tid 140033488463616] [remote ::1:34844] [[0.13894767 0.2243983  0.6366541 ]]
[Mon May 24 21:30:54.396514 2021] [wsgi:error] [pid 24049:tid 140033480070912] [remote ::1:34846] [[5.4134727e-02 1.4948583e-04 9.4571579e-01]]
[Mon May 24 21:30:54.441482 2021] [wsgi:error] [pid 24049:tid 140033488463616] [remote ::1:34844] [[0.00771133 0.00438042 0.9879083 ]]
[Mon May 24 21:30:54.525403 2021] [wsgi:error] [pid 24049:tid 140033480070912] [remote ::1:34846] [[0.00515046 0.137072   0.85777754]]
[Mon May 24 21:30:54.561960 2021] [wsgi:error] [pid 24049:tid 140033488463616] [remote ::1:34844] [[5.4134727e-02 1.4948583e-04 9.4571579e-01]]
[Mon May 24 21:30:54.683692 2021] [wsgi:error] [pid 24049:tid 140033480070912] [remote ::1:34846] [[0.02074791 0.01212754 0.9671245 ]]
[Mon May 24 21:30:54.746561 2021] [wsgi:error] [pid 24049:tid 140033488463616] [remote ::1:34844] [[0.00515046 0.137072   0.85777754]]
[Mon May 24 21:30:54.874216 2021] [wsgi:error] [pid 24049:tid 140033480070912] [remote ::1:34846] [[0.00525339 0.02359281 0.9711538 ]]
[Mon May 24 21:30:54.950880 2021] [wsgi:error] [pid 24049:tid 140033488463616] [remote ::1:34844] [[0.02074791 0.01212754 0.9671245 ]]
[Mon May 24 21:30:55.052573 2021] [wsgi:error] [pid 24049:tid 140033480070912] [remote ::1:34846] [[0.0428966  0.03135791 0.9257454 ]]
[Mon May 24 21:30:55.138168 2021] [wsgi:error] [pid 24049:tid 140033488463616] [remote ::1:34844] [[0.00525339 0.02359281 0.9711538 ]]
[Mon May 24 21:30:55.240112 2021] [wsgi:error] [pid 24049:tid 140033480070912] [remote ::1:34846] [[0.3347329  0.10236973 0.56289744]]
[Mon May 24 21:30:55.317750 2021] [wsgi:error] [pid 24049:tid 140033488463616] [remote ::1:34844] [[0.0428966  0.03135791 0.9257454 ]]
[Mon May 24 21:30:55.478965 2021] [wsgi:error] [pid 24049:tid 140033488463616] [remote ::1:34844] [[0.3347329  0.10236973 0.56289744]]
[Mon May 24 21:30:55.564684 2021] [wsgi:error] [pid 24049:tid 140033480070912] [remote ::1:34846] [[1.2683483e-02 2.6598462e-04 9.8705053e-01]]
[Mon May 24 21:30:55.685859 2021] [wsgi:error] [pid 24049:tid 140033480070912] [remote ::1:34846] [[9.351187e-03 5.857703e-04 9.900630e-01]]
[Mon May 24 21:30:55.714043 2021] [wsgi:error] [pid 24049:tid 140033488463616] [remote ::1:34844] [[1.2683483e-02 2.6598462e-04 9.8705053e-01]]
[Mon May 24 21:30:55.790177 2021] [wsgi:error] [pid 24049:tid 140033480070912] [remote ::1:34846] [[2.0315698e-01 5.8732134e-05 7.9678428e-01]]
[Mon May 24 21:30:55.824849 2021] [wsgi:error] [pid 24049:tid 140033488463616] [remote ::1:34844] [[9.351187e-03 5.857703e-04 9.900630e-01]]
[Mon May 24 21:30:55.917630 2021] [wsgi:error] [pid 24049:tid 140033480070912] [remote ::1:34846] [[1.3129169e-01 3.9674775e-04 8.6831158e-01]]
[Mon May 24 21:30:55.939913 2021] [wsgi:error] [pid 24049:tid 140033488463616] [remote ::1:34844] [[2.0315698e-01 5.8732134e-05 7.9678428e-01]]
[Mon May 24 21:30:56.045609 2021] [wsgi:error] [pid 24049:tid 140033480070912] [remote ::1:34846] [[0.01497851 0.0282674  0.956754  ]]
[Mon May 24 21:30:56.069611 2021] [wsgi:error] [pid 24049:tid 140033488463616] [remote ::1:34844] [[1.3129169e-01 3.9674775e-04 8.6831158e-01]]
[Mon May 24 21:30:56.196283 2021] [wsgi:error] [pid 24049:tid 140033480070912] [remote ::1:34846] [[0.01563484 0.00168601 0.9826791 ]]
[Mon May 24 21:30:56.200621 2021] [wsgi:error] [pid 24049:tid 140033488463616] [remote ::1:34844] [[0.01497851 0.0282674  0.956754  ]]
[Mon May 24 21:30:56.398692 2021] [wsgi:error] [pid 24049:tid 140033488463616] [remote ::1:34844] [[0.01563484 0.00168601 0.9826791 ]]
[Mon May 24 21:30:56.399387 2021] [wsgi:error] [pid 24049:tid 140033480070912] [remote ::1:34846] [[0.0962153  0.00161867 0.90216607]]
[Mon May 24 21:30:56.568275 2021] [wsgi:error] [pid 24049:tid 140033480070912] [remote ::1:34846] [[0.113419   0.00143218 0.8851489 ]]
[Mon May 24 21:30:56.577740 2021] [wsgi:error] [pid 24049:tid 140033488463616] [remote ::1:34844] [[0.0962153  0.00161867 0.90216607]]
[Mon May 24 21:30:56.680242 2021] [wsgi:error] [pid 24049:tid 140033480070912] [remote ::1:34846] [[4.0270045e-01 3.2915789e-04 5.9697032e-01]]
[Mon May 24 21:30:56.717776 2021] [wsgi:error] [pid 24049:tid 140033488463616] [remote ::1:34844] [[0.113419   0.00143218 0.8851489 ]]
[Mon May 24 21:30:56.819483 2021] [wsgi:error] [pid 24049:tid 140033480070912] [remote ::1:34846] [[0.01356036 0.00146619 0.98497343]]
[Mon May 24 21:30:56.853893 2021] [wsgi:error] [pid 24049:tid 140033488463616] [remote ::1:34844] [[4.0270045e-01 3.2915789e-04 5.9697032e-01]]
[Mon May 24 21:30:56.955147 2021] [wsgi:error] [pid 24049:tid 140033480070912] [remote ::1:34846] [[0.10555577 0.00237805 0.89206624]]
[Mon May 24 21:30:57.023919 2021] [wsgi:error] [pid 24049:tid 140033488463616] [remote ::1:34844] [[0.01356036 0.00146619 0.98497343]]
[Mon May 24 21:30:57.219896 2021] [wsgi:error] [pid 24049:tid 140033480070912] [remote ::1:34846] [[0.0390755  0.00220466 0.95871985]]
[Mon May 24 21:30:57.301419 2021] [wsgi:error] [pid 24049:tid 140033488463616] [remote ::1:34844] [[0.10555577 0.00237805 0.89206624]]
[Mon May 24 21:30:57.487055 2021] [wsgi:error] [pid 24049:tid 140033480070912] [remote ::1:34846] [[0.3756094  0.00065641 0.6237342 ]]
[Mon May 24 21:30:57.559709 2021] [wsgi:error] [pid 24049:tid 140033488463616] [remote ::1:34844] [[0.0390755  0.00220466 0.95871985]]
[Mon May 24 21:30:57.699471 2021] [wsgi:error] [pid 24049:tid 140033480070912] [remote ::1:34846] [[0.23184894 0.01046115 0.75768995]]
[Mon May 24 21:30:57.773816 2021] [wsgi:error] [pid 24049:tid 140033488463616] [remote ::1:34844] [[0.3756094  0.00065641 0.6237342 ]]
[Mon May 24 21:30:57.915283 2021] [wsgi:error] [pid 24049:tid 140033480070912] [remote ::1:34846] [[0.05170992 0.04311773 0.90517235]]
[Mon May 24 21:30:57.988171 2021] [wsgi:error] [pid 24049:tid 140033488463616] [remote ::1:34844] [[0.23184894 0.01046115 0.75768995]]
[Mon May 24 21:30:58.252194 2021] [wsgi:error] [pid 24049:tid 140033480070912] [remote ::1:34846] [[0.06273152 0.00819713 0.9290714 ]]
[Mon May 24 21:30:58.311849 2021] [wsgi:error] [pid 24049:tid 140033488463616] [remote ::1:34844] [[0.05170992 0.04311773 0.90517235]]
[Mon May 24 21:30:58.510109 2021] [wsgi:error] [pid 24049:tid 140033480070912] [remote ::1:34846] [[0.00867269 0.00710053 0.98422676]]
[Mon May 24 21:30:58.612386 2021] [wsgi:error] [pid 24049:tid 140033488463616] [remote ::1:34844] [[0.06273152 0.00819713 0.9290714 ]]
[Mon May 24 21:30:58.756031 2021] [wsgi:error] [pid 24049:tid 140033480070912] [remote ::1:34846] [[0.16794285 0.00228982 0.8297674 ]]
[Mon May 24 21:30:58.848017 2021] [wsgi:error] [pid 24049:tid 140033488463616] [remote ::1:34844] [[0.00867269 0.00710053 0.98422676]]
[Mon May 24 21:30:58.904277 2021] [wsgi:error] [pid 24049:tid 140033480070912] [remote ::1:34846] [[0.10094725 0.00250942 0.8965433 ]]
[Mon May 24 21:30:58.948889 2021] [wsgi:error] [pid 24049:tid 140033488463616] [remote ::1:34844] [[0.16794285 0.00228982 0.8297674 ]]
[Mon May 24 21:30:59.130441 2021] [wsgi:error] [pid 24049:tid 140033488463616] [remote ::1:34844] [[0.10094725 0.00250942 0.8965433 ]]
[Mon May 24 21:30:59.155587 2021] [wsgi:error] [pid 24049:tid 140033480070912] [remote ::1:34846] [[4.0272083e-02 6.9289043e-04 9.5903498e-01]]
[Mon May 24 21:30:59.420825 2021] [wsgi:error] [pid 24049:tid 140033488463616] [remote ::1:34844] [[4.0272083e-02 6.9289043e-04 9.5903498e-01]]
2021-05-24 21:30:02.726970: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2021-05-24 21:30:02.727052: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2021-05-24 21:30:16.452886: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2021-05-24 21:30:16.452914: W tensorflow/stream_executor/cuda/cuda_driver.cc:326] failed call to cuInit: UNKNOWN ERROR (303)
2021-05-24 21:30:16.452934: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (DESKTOP-MNQ7F8E): /proc/driver/nvidia/version does not exist
2021-05-24 21:30:16.453228: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2021-05-24 21:30:20.718467: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:176] None of the MLIR Optimization Passes are enabled (registered 2)
2021-05-24 21:30:20.719121: I tensorflow/core/platform/profile_utils/cpu_utils.cc:114] CPU Frequency: 1991995000 Hz
2021-05-24 21:38:44.703747: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2021-05-24 21:38:44.703789: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2021-05-24 21:46:24.369020: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2021-05-24 21:46:24.369050: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2021-05-24 21:54:43.059942: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2021-05-24 21:54:43.059988: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2021-05-24 21:55:28.049709: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2021-05-24 21:55:28.049743: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2021-05-24 21:56:51.231014: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2021-05-24 21:56:51.231043: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2021-05-24 22:23:08.397447: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2021-05-24 22:23:08.397489: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2021-05-24 22:23:53.213192: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2021-05-24 22:23:53.213221: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2021-05-24 22:25:06.151708: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2021-05-24 22:25:06.151785: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2021-05-24 22:28:53.415789: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2021-05-24 22:28:53.415820: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2021-05-24 22:29:38.061893: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2021-05-24 22:29:38.061932: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2021-05-25 16:56:52.333336: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2021-05-25 16:56:52.333412: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
[Tue May 25 17:07:22.567409 2021] [wsgi:error] [pid 26295:tid 140098086016768] [remote ::1:34970] [2021-05-25 17:07:22,563] ERROR in app: Exception on /emotion_prediction [POST]
[Tue May 25 17:07:22.567464 2021] [wsgi:error] [pid 26295:tid 140098086016768] [remote ::1:34970] Traceback (most recent call last):
[Tue May 25 17:07:22.567472 2021] [wsgi:error] [pid 26295:tid 140098086016768] [remote ::1:34970]   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2051, in wsgi_app
[Tue May 25 17:07:22.567479 2021] [wsgi:error] [pid 26295:tid 140098086016768] [remote ::1:34970]     response = self.full_dispatch_request()
[Tue May 25 17:07:22.567484 2021] [wsgi:error] [pid 26295:tid 140098086016768] [remote ::1:34970]   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1501, in full_dispatch_request
[Tue May 25 17:07:22.567490 2021] [wsgi:error] [pid 26295:tid 140098086016768] [remote ::1:34970]     rv = self.handle_user_exception(e)
[Tue May 25 17:07:22.567495 2021] [wsgi:error] [pid 26295:tid 140098086016768] [remote ::1:34970]   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1499, in full_dispatch_request
[Tue May 25 17:07:22.567501 2021] [wsgi:error] [pid 26295:tid 140098086016768] [remote ::1:34970]     rv = self.dispatch_request()
[Tue May 25 17:07:22.567506 2021] [wsgi:error] [pid 26295:tid 140098086016768] [remote ::1:34970]   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1485, in dispatch_request
[Tue May 25 17:07:22.567512 2021] [wsgi:error] [pid 26295:tid 140098086016768] [remote ::1:34970]     return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
[Tue May 25 17:07:22.567517 2021] [wsgi:error] [pid 26295:tid 140098086016768] [remote ::1:34970]   File "/home/copes/graduation-project/Web/app.py", line 44, in emotion_prediction
[Tue May 25 17:07:22.567523 2021] [wsgi:error] [pid 26295:tid 140098086016768] [remote ::1:34970]     model = load_model('home/copes/graduation-project/Web/models/model_best_0_2.h5')
[Tue May 25 17:07:22.567529 2021] [wsgi:error] [pid 26295:tid 140098086016768] [remote ::1:34970]   File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/keras/saving/save.py", line 206, in load_model
[Tue May 25 17:07:22.567535 2021] [wsgi:error] [pid 26295:tid 140098086016768] [remote ::1:34970]     return saved_model_load.load(filepath, compile, options)
[Tue May 25 17:07:22.567540 2021] [wsgi:error] [pid 26295:tid 140098086016768] [remote ::1:34970]   File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/keras/saving/saved_model/load.py", line 121, in load
[Tue May 25 17:07:22.567546 2021] [wsgi:error] [pid 26295:tid 140098086016768] [remote ::1:34970]     meta_graph_def = loader_impl.parse_saved_model(path).meta_graphs[0]
[Tue May 25 17:07:22.567551 2021] [wsgi:error] [pid 26295:tid 140098086016768] [remote ::1:34970]   File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/saved_model/loader_impl.py", line 113, in parse_saved_model
[Tue May 25 17:07:22.567557 2021] [wsgi:error] [pid 26295:tid 140098086016768] [remote ::1:34970]     raise IOError(
[Tue May 25 17:07:22.567562 2021] [wsgi:error] [pid 26295:tid 140098086016768] [remote ::1:34970] OSError: SavedModel file does not exist at: home/copes/graduation-project/Web/models/model_best_0_2.h5/{saved_model.pbtxt|saved_model.pb}
[Tue May 25 17:07:46.375075 2021] [wsgi:error] [pid 26295:tid 140098086016768] [remote ::1:34974] [2021-05-25 17:07:46,373] ERROR in app: Exception on /multi_upload_gan [POST]
[Tue May 25 17:07:46.375116 2021] [wsgi:error] [pid 26295:tid 140098086016768] [remote ::1:34974] Traceback (most recent call last):
[Tue May 25 17:07:46.375123 2021] [wsgi:error] [pid 26295:tid 140098086016768] [remote ::1:34974]   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2051, in wsgi_app
[Tue May 25 17:07:46.375129 2021] [wsgi:error] [pid 26295:tid 140098086016768] [remote ::1:34974]     response = self.full_dispatch_request()
[Tue May 25 17:07:46.375134 2021] [wsgi:error] [pid 26295:tid 140098086016768] [remote ::1:34974]   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1501, in full_dispatch_request
[Tue May 25 17:07:46.375152 2021] [wsgi:error] [pid 26295:tid 140098086016768] [remote ::1:34974]     rv = self.handle_user_exception(e)
[Tue May 25 17:07:46.375157 2021] [wsgi:error] [pid 26295:tid 140098086016768] [remote ::1:34974]   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1499, in full_dispatch_request
[Tue May 25 17:07:46.375197 2021] [wsgi:error] [pid 26295:tid 140098086016768] [remote ::1:34974]     rv = self.dispatch_request()
[Tue May 25 17:07:46.375207 2021] [wsgi:error] [pid 26295:tid 140098086016768] [remote ::1:34974]   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1485, in dispatch_request
[Tue May 25 17:07:46.375214 2021] [wsgi:error] [pid 26295:tid 140098086016768] [remote ::1:34974]     return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
[Tue May 25 17:07:46.375222 2021] [wsgi:error] [pid 26295:tid 140098086016768] [remote ::1:34974]   File "/home/copes/graduation-project/Web/app.py", line 30, in multi_upload_gan
[Tue May 25 17:07:46.375238 2021] [wsgi:error] [pid 26295:tid 140098086016768] [remote ::1:34974]     file.save("home/copes/graduation-project/Web/static/GAN/{}.jpg".format(IDX))
[Tue May 25 17:07:46.375247 2021] [wsgi:error] [pid 26295:tid 140098086016768] [remote ::1:34974]   File "/usr/local/lib/python3.8/dist-packages/werkzeug/datastructures.py", line 3013, in save
[Tue May 25 17:07:46.375255 2021] [wsgi:error] [pid 26295:tid 140098086016768] [remote ::1:34974]     dst = open(dst, "wb")
[Tue May 25 17:07:46.375263 2021] [wsgi:error] [pid 26295:tid 140098086016768] [remote ::1:34974] FileNotFoundError: [Errno 2] No such file or directory: 'home/copes/graduation-project/Web/static/GAN/0.jpg'
[Tue May 25 17:11:16.041608 2021] [wsgi:error] [pid 26295:tid 140098119587584] [remote ::1:34978] [2021-05-25 17:11:16,040] ERROR in app: Exception on /emotion_prediction [POST]
[Tue May 25 17:11:16.041684 2021] [wsgi:error] [pid 26295:tid 140098119587584] [remote ::1:34978] Traceback (most recent call last):
[Tue May 25 17:11:16.041698 2021] [wsgi:error] [pid 26295:tid 140098119587584] [remote ::1:34978]   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2051, in wsgi_app
[Tue May 25 17:11:16.041707 2021] [wsgi:error] [pid 26295:tid 140098119587584] [remote ::1:34978]     response = self.full_dispatch_request()
[Tue May 25 17:11:16.041715 2021] [wsgi:error] [pid 26295:tid 140098119587584] [remote ::1:34978]   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1501, in full_dispatch_request
[Tue May 25 17:11:16.041723 2021] [wsgi:error] [pid 26295:tid 140098119587584] [remote ::1:34978]     rv = self.handle_user_exception(e)
[Tue May 25 17:11:16.041730 2021] [wsgi:error] [pid 26295:tid 140098119587584] [remote ::1:34978]   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1499, in full_dispatch_request
[Tue May 25 17:11:16.041738 2021] [wsgi:error] [pid 26295:tid 140098119587584] [remote ::1:34978]     rv = self.dispatch_request()
[Tue May 25 17:11:16.041745 2021] [wsgi:error] [pid 26295:tid 140098119587584] [remote ::1:34978]   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1485, in dispatch_request
[Tue May 25 17:11:16.041752 2021] [wsgi:error] [pid 26295:tid 140098119587584] [remote ::1:34978]     return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
[Tue May 25 17:11:16.041759 2021] [wsgi:error] [pid 26295:tid 140098119587584] [remote ::1:34978]   File "/home/copes/graduation-project/Web/app.py", line 44, in emotion_prediction
[Tue May 25 17:11:16.041765 2021] [wsgi:error] [pid 26295:tid 140098119587584] [remote ::1:34978]     model = load_model('home/copes/graduation-project/Web/models/model_best_0_2.h5')
[Tue May 25 17:11:16.041773 2021] [wsgi:error] [pid 26295:tid 140098119587584] [remote ::1:34978]   File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/keras/saving/save.py", line 206, in load_model
[Tue May 25 17:11:16.041780 2021] [wsgi:error] [pid 26295:tid 140098119587584] [remote ::1:34978]     return saved_model_load.load(filepath, compile, options)
[Tue May 25 17:11:16.041800 2021] [wsgi:error] [pid 26295:tid 140098119587584] [remote ::1:34978]   File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/keras/saving/saved_model/load.py", line 121, in load
[Tue May 25 17:11:16.041807 2021] [wsgi:error] [pid 26295:tid 140098119587584] [remote ::1:34978]     meta_graph_def = loader_impl.parse_saved_model(path).meta_graphs[0]
[Tue May 25 17:11:16.041814 2021] [wsgi:error] [pid 26295:tid 140098119587584] [remote ::1:34978]   File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/saved_model/loader_impl.py", line 113, in parse_saved_model
[Tue May 25 17:11:16.041820 2021] [wsgi:error] [pid 26295:tid 140098119587584] [remote ::1:34978]     raise IOError(
[Tue May 25 17:11:16.041826 2021] [wsgi:error] [pid 26295:tid 140098119587584] [remote ::1:34978] OSError: SavedModel file does not exist at: home/copes/graduation-project/Web/models/model_best_0_2.h5/{saved_model.pbtxt|saved_model.pb}
[Tue May 25 17:11:20.661109 2021] [wsgi:error] [pid 26295:tid 140098086016768] [remote ::1:34980] [2021-05-25 17:11:20,660] ERROR in app: Exception on /emotion_prediction [POST]
[Tue May 25 17:11:20.661204 2021] [wsgi:error] [pid 26295:tid 140098086016768] [remote ::1:34980] Traceback (most recent call last):
[Tue May 25 17:11:20.661217 2021] [wsgi:error] [pid 26295:tid 140098086016768] [remote ::1:34980]   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2051, in wsgi_app
[Tue May 25 17:11:20.661227 2021] [wsgi:error] [pid 26295:tid 140098086016768] [remote ::1:34980]     response = self.full_dispatch_request()
[Tue May 25 17:11:20.661235 2021] [wsgi:error] [pid 26295:tid 140098086016768] [remote ::1:34980]   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1501, in full_dispatch_request
[Tue May 25 17:11:20.661243 2021] [wsgi:error] [pid 26295:tid 140098086016768] [remote ::1:34980]     rv = self.handle_user_exception(e)
[Tue May 25 17:11:20.661250 2021] [wsgi:error] [pid 26295:tid 140098086016768] [remote ::1:34980]   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1499, in full_dispatch_request
[Tue May 25 17:11:20.661257 2021] [wsgi:error] [pid 26295:tid 140098086016768] [remote ::1:34980]     rv = self.dispatch_request()
[Tue May 25 17:11:20.661264 2021] [wsgi:error] [pid 26295:tid 140098086016768] [remote ::1:34980]   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1485, in dispatch_request
[Tue May 25 17:11:20.661273 2021] [wsgi:error] [pid 26295:tid 140098086016768] [remote ::1:34980]     return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
[Tue May 25 17:11:20.661280 2021] [wsgi:error] [pid 26295:tid 140098086016768] [remote ::1:34980]   File "/home/copes/graduation-project/Web/app.py", line 44, in emotion_prediction
[Tue May 25 17:11:20.661288 2021] [wsgi:error] [pid 26295:tid 140098086016768] [remote ::1:34980]     model = load_model('home/copes/graduation-project/Web/models/model_best_0_2.h5')
[Tue May 25 17:11:20.661296 2021] [wsgi:error] [pid 26295:tid 140098086016768] [remote ::1:34980]   File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/keras/saving/save.py", line 206, in load_model
[Tue May 25 17:11:20.661306 2021] [wsgi:error] [pid 26295:tid 140098086016768] [remote ::1:34980]     return saved_model_load.load(filepath, compile, options)
[Tue May 25 17:11:20.661313 2021] [wsgi:error] [pid 26295:tid 140098086016768] [remote ::1:34980]   File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/keras/saving/saved_model/load.py", line 121, in load
[Tue May 25 17:11:20.661322 2021] [wsgi:error] [pid 26295:tid 140098086016768] [remote ::1:34980]     meta_graph_def = loader_impl.parse_saved_model(path).meta_graphs[0]
[Tue May 25 17:11:20.661331 2021] [wsgi:error] [pid 26295:tid 140098086016768] [remote ::1:34980]   File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/saved_model/loader_impl.py", line 113, in parse_saved_model
[Tue May 25 17:11:20.661375 2021] [wsgi:error] [pid 26295:tid 140098086016768] [remote ::1:34980]     raise IOError(
[Tue May 25 17:11:20.661384 2021] [wsgi:error] [pid 26295:tid 140098086016768] [remote ::1:34980] OSError: SavedModel file does not exist at: home/copes/graduation-project/Web/models/model_best_0_2.h5/{saved_model.pbtxt|saved_model.pb}
[Tue May 25 17:12:50.252625 2021] [wsgi:error] [pid 26295:tid 140098119587584] [remote ::1:34984] [2021-05-25 17:12:50,252] ERROR in app: Exception on /multi_upload_gan [POST]
[Tue May 25 17:12:50.252709 2021] [wsgi:error] [pid 26295:tid 140098119587584] [remote ::1:34984] Traceback (most recent call last):
[Tue May 25 17:12:50.252721 2021] [wsgi:error] [pid 26295:tid 140098119587584] [remote ::1:34984]   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2051, in wsgi_app
[Tue May 25 17:12:50.252727 2021] [wsgi:error] [pid 26295:tid 140098119587584] [remote ::1:34984]     response = self.full_dispatch_request()
[Tue May 25 17:12:50.252733 2021] [wsgi:error] [pid 26295:tid 140098119587584] [remote ::1:34984]   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1501, in full_dispatch_request
[Tue May 25 17:12:50.252740 2021] [wsgi:error] [pid 26295:tid 140098119587584] [remote ::1:34984]     rv = self.handle_user_exception(e)
[Tue May 25 17:12:50.252751 2021] [wsgi:error] [pid 26295:tid 140098119587584] [remote ::1:34984]   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1499, in full_dispatch_request
[Tue May 25 17:12:50.252764 2021] [wsgi:error] [pid 26295:tid 140098119587584] [remote ::1:34984]     rv = self.dispatch_request()
[Tue May 25 17:12:50.252773 2021] [wsgi:error] [pid 26295:tid 140098119587584] [remote ::1:34984]   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1485, in dispatch_request
[Tue May 25 17:12:50.252781 2021] [wsgi:error] [pid 26295:tid 140098119587584] [remote ::1:34984]     return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
[Tue May 25 17:12:50.252788 2021] [wsgi:error] [pid 26295:tid 140098119587584] [remote ::1:34984]   File "/home/copes/graduation-project/Web/app.py", line 30, in multi_upload_gan
[Tue May 25 17:12:50.252795 2021] [wsgi:error] [pid 26295:tid 140098119587584] [remote ::1:34984]     file.save("home/copes/graduation-project/Web/static/GAN/{}.jpg".format(IDX))
[Tue May 25 17:12:50.252802 2021] [wsgi:error] [pid 26295:tid 140098119587584] [remote ::1:34984]   File "/usr/local/lib/python3.8/dist-packages/werkzeug/datastructures.py", line 3013, in save
[Tue May 25 17:12:50.252809 2021] [wsgi:error] [pid 26295:tid 140098119587584] [remote ::1:34984]     dst = open(dst, "wb")
[Tue May 25 17:12:50.252817 2021] [wsgi:error] [pid 26295:tid 140098119587584] [remote ::1:34984] FileNotFoundError: [Errno 2] No such file or directory: 'home/copes/graduation-project/Web/static/GAN/0.jpg'
2021-05-25 17:07:02.622073: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2021-05-25 17:07:02.622122: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
[Tue May 25 17:14:01.206924 2021] [wsgi:error] [pid 26430:tid 139796851840768] [remote ::1:34986] [2021-05-25 17:14:01,202] ERROR in app: Exception on /multi_upload_gan [POST]
[Tue May 25 17:14:01.207182 2021] [wsgi:error] [pid 26430:tid 139796851840768] [remote ::1:34986] Traceback (most recent call last):
[Tue May 25 17:14:01.207214 2021] [wsgi:error] [pid 26430:tid 139796851840768] [remote ::1:34986]   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2051, in wsgi_app
[Tue May 25 17:14:01.207229 2021] [wsgi:error] [pid 26430:tid 139796851840768] [remote ::1:34986]     response = self.full_dispatch_request()
[Tue May 25 17:14:01.207242 2021] [wsgi:error] [pid 26430:tid 139796851840768] [remote ::1:34986]   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1501, in full_dispatch_request
[Tue May 25 17:14:01.207279 2021] [wsgi:error] [pid 26430:tid 139796851840768] [remote ::1:34986]     rv = self.handle_user_exception(e)
[Tue May 25 17:14:01.207291 2021] [wsgi:error] [pid 26430:tid 139796851840768] [remote ::1:34986]   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1499, in full_dispatch_request
[Tue May 25 17:14:01.207302 2021] [wsgi:error] [pid 26430:tid 139796851840768] [remote ::1:34986]     rv = self.dispatch_request()
[Tue May 25 17:14:01.207312 2021] [wsgi:error] [pid 26430:tid 139796851840768] [remote ::1:34986]   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1485, in dispatch_request
[Tue May 25 17:14:01.207324 2021] [wsgi:error] [pid 26430:tid 139796851840768] [remote ::1:34986]     return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
[Tue May 25 17:14:01.207335 2021] [wsgi:error] [pid 26430:tid 139796851840768] [remote ::1:34986]   File "/home/copes/graduation-project/Web/app.py", line 30, in multi_upload_gan
[Tue May 25 17:14:01.207345 2021] [wsgi:error] [pid 26430:tid 139796851840768] [remote ::1:34986]     file.save("/home/copes/graduation-project/Web/static/GAN/{}.jpg".format(IDX))
[Tue May 25 17:14:01.207355 2021] [wsgi:error] [pid 26430:tid 139796851840768] [remote ::1:34986]   File "/usr/local/lib/python3.8/dist-packages/werkzeug/datastructures.py", line 3013, in save
[Tue May 25 17:14:01.207366 2021] [wsgi:error] [pid 26430:tid 139796851840768] [remote ::1:34986]     dst = open(dst, "wb")
[Tue May 25 17:14:01.207375 2021] [wsgi:error] [pid 26430:tid 139796851840768] [remote ::1:34986] PermissionError: [Errno 13] Permission denied: '/home/copes/graduation-project/Web/static/GAN/0.jpg'
2021-05-25 17:13:58.754412: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2021-05-25 17:13:58.754440: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
[Tue May 25 17:16:00.762573 2021] [wsgi:error] [pid 26574:tid 140425293965056] [remote ::1:34990] [[9.6297739e-03 9.1982674e-04 9.8945040e-01]]
[Tue May 25 17:16:00.894580 2021] [wsgi:error] [pid 26574:tid 140425293965056] [remote ::1:34990] [[0.02050695 0.06258767 0.9169054 ]]
[Tue May 25 17:16:01.055943 2021] [wsgi:error] [pid 26574:tid 140425293965056] [remote ::1:34990] [[0.1561424  0.00467606 0.83918154]]
[Tue May 25 17:16:01.225652 2021] [wsgi:error] [pid 26574:tid 140425293965056] [remote ::1:34990] [[0.00845459 0.00888204 0.9826634 ]]
[Tue May 25 17:16:01.380603 2021] [wsgi:error] [pid 26574:tid 140425293965056] [remote ::1:34990] [[4.597729e-02 3.666400e-04 9.536561e-01]]
[Tue May 25 17:16:01.573409 2021] [wsgi:error] [pid 26574:tid 140425293965056] [remote ::1:34990] [[0.02591931 0.00367296 0.9704077 ]]
[Tue May 25 17:16:01.747154 2021] [wsgi:error] [pid 26574:tid 140425293965056] [remote ::1:34990] [[0.00273046 0.0191434  0.9781261 ]]
[Tue May 25 17:16:02.253922 2021] [wsgi:error] [pid 26574:tid 140425293965056] [remote ::1:34990] [[0.05130138 0.00247891 0.94621974]]
[Tue May 25 17:16:02.428754 2021] [wsgi:error] [pid 26574:tid 140425293965056] [remote ::1:34990] [[0.0045835  0.00117963 0.9942368 ]]
[Tue May 25 17:16:02.584866 2021] [wsgi:error] [pid 26574:tid 140425293965056] [remote ::1:34990] [[4.8797271e-01 3.9616763e-04 5.1163113e-01]]
[Tue May 25 17:16:02.745036 2021] [wsgi:error] [pid 26574:tid 140425293965056] [remote ::1:34990] [[6.1493507e-03 6.6049478e-04 9.9319011e-01]]
[Tue May 25 17:16:02.913569 2021] [wsgi:error] [pid 26574:tid 140425293965056] [remote ::1:34990] [[7.2099008e-02 2.0876895e-04 9.2769223e-01]]
[Tue May 25 17:16:03.076367 2021] [wsgi:error] [pid 26574:tid 140425293965056] [remote ::1:34990] [[0.0311581  0.01410805 0.9547339 ]]
[Tue May 25 17:16:03.221919 2021] [wsgi:error] [pid 26574:tid 140425293965056] [remote ::1:34990] [[4.3041032e-02 1.7129301e-04 9.5678765e-01]]
[Tue May 25 17:16:03.575571 2021] [wsgi:error] [pid 26574:tid 140425293965056] [remote ::1:34990] [[0.19477195 0.00555172 0.79967636]]
[Tue May 25 17:16:03.745318 2021] [wsgi:error] [pid 26574:tid 140425293965056] [remote ::1:34990] [[0.0181159  0.00715475 0.9747293 ]]
[Tue May 25 17:16:03.906268 2021] [wsgi:error] [pid 26574:tid 140425293965056] [remote ::1:34990] [[0.00215236 0.14575163 0.85209596]]
[Tue May 25 17:16:04.076035 2021] [wsgi:error] [pid 26574:tid 140425293965056] [remote ::1:34990] [[0.01975805 0.00176907 0.9784728 ]]
[Tue May 25 17:16:04.253342 2021] [wsgi:error] [pid 26574:tid 140425293965056] [remote ::1:34990] [[1.5929326e-01 6.4941193e-04 8.4005737e-01]]
[Tue May 25 17:16:04.458624 2021] [wsgi:error] [pid 26574:tid 140425293965056] [remote ::1:34990] [[0.10447256 0.00173842 0.89378893]]
[Tue May 25 17:16:04.678763 2021] [wsgi:error] [pid 26574:tid 140425293965056] [remote ::1:34990] [[1.9839752e-02 3.9648614e-04 9.7976375e-01]]
[Tue May 25 17:16:04.892442 2021] [wsgi:error] [pid 26574:tid 140425293965056] [remote ::1:34990] [[4.0209842e-01 5.7689834e-04 5.9732479e-01]]
[Tue May 25 17:16:05.113465 2021] [wsgi:error] [pid 26574:tid 140425293965056] [remote ::1:34990] [[0.1287375  0.0066506  0.86461186]]
[Tue May 25 17:16:05.326862 2021] [wsgi:error] [pid 26574:tid 140425293965056] [remote ::1:34990] [[1.8442921e-02 3.1668242e-05 9.8152542e-01]]
[Tue May 25 17:16:05.511574 2021] [wsgi:error] [pid 26574:tid 140425293965056] [remote ::1:34990] [[0.11244605 0.03096933 0.85658467]]
[Tue May 25 17:16:05.683771 2021] [wsgi:error] [pid 26574:tid 140425293965056] [remote ::1:34990] [[0.31806996 0.00182547 0.68010455]]
[Tue May 25 17:16:05.840019 2021] [wsgi:error] [pid 26574:tid 140425293965056] [remote ::1:34990] [[1.0387175e-01 6.4992596e-04 8.9547831e-01]]
[Tue May 25 17:16:06.040934 2021] [wsgi:error] [pid 26574:tid 140425293965056] [remote ::1:34990] [[1.4036876e-01 2.9067480e-04 8.5934049e-01]]
[Tue May 25 17:16:06.191435 2021] [wsgi:error] [pid 26574:tid 140425293965056] [remote ::1:34990] [[0.03275191 0.08921272 0.8780354 ]]
[Tue May 25 17:16:06.325263 2021] [wsgi:error] [pid 26574:tid 140425293965056] [remote ::1:34990] [[0.11591227 0.00254197 0.8815458 ]]
[Tue May 25 17:16:06.477385 2021] [wsgi:error] [pid 26574:tid 140425293965056] [remote ::1:34990] [[0.13894767 0.2243983  0.6366541 ]]
[Tue May 25 17:16:06.639596 2021] [wsgi:error] [pid 26574:tid 140425293965056] [remote ::1:34990] [[0.00771133 0.00438042 0.9879083 ]]
[Tue May 25 17:16:06.798543 2021] [wsgi:error] [pid 26574:tid 140425293965056] [remote ::1:34990] [[5.4134727e-02 1.4948583e-04 9.4571579e-01]]
[Tue May 25 17:16:07.002198 2021] [wsgi:error] [pid 26574:tid 140425293965056] [remote ::1:34990] [[0.00515046 0.137072   0.85777754]]
[Tue May 25 17:16:07.247134 2021] [wsgi:error] [pid 26574:tid 140425293965056] [remote ::1:34990] [[0.02074791 0.01212754 0.9671245 ]]
[Tue May 25 17:16:07.540458 2021] [wsgi:error] [pid 26574:tid 140425293965056] [remote ::1:34990] [[0.00525339 0.02359281 0.9711538 ]]
[Tue May 25 17:16:07.840276 2021] [wsgi:error] [pid 26574:tid 140425293965056] [remote ::1:34990] [[0.0428966  0.03135791 0.9257454 ]]
[Tue May 25 17:16:08.043651 2021] [wsgi:error] [pid 26574:tid 140425293965056] [remote ::1:34990] [[0.3347329  0.10236973 0.56289744]]
